apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synologi-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:LmrFZ3q4O1QE2vntEwgCJCQotlYIxk288rCvlevVoh38j9007CvLDzFOtmedqMPjU1JmkqJU1uztW28DoJViBgrJJ0L9WO+eUBMH7vMsvWcewhlkB/PAf/y3wV9WA92G8Vlk3UZvFxzUDKq+6BJYw2Y0sjpc51vmi275qIro2l4qF08MkH8Y2ib0mJPh4/SP5UF8P+liH/0Y1J0oTqtc/KnmHKKSkQnLfk4Qz+/6t1EP826VsIBXf5XZ0ko67xQFMJdC0fUe7xQq+MxYjIYJrYx3,iv:bSsiUVmI1x7EGit/8dEgL1yxZkAH/Sz5flF49RP0NSY=,tag:VqF3P1JIPd/SNNZWSwJzkA==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHRqNlNnbmlI
            cTFERE8vSkk0U0ZsdWVKdGZ5V2tEbkRiZFhBalQ4MHQzTmhqUkYwNm0xRlZ0ckVI
            cTNTanBwY2Y3ZVFoK0E1QzFobzcvZ0NBOUpMaEMyMThEdk4wRm5SVm1YREdYbC93
            OUxoYUgrOS9zV09ucjAwTkdscUFPcWR3dTB4azNnaDZIemNwTHB5NXV4VGFqdnV6
            RGJrbHBUSzloQWt6WjFxRHRqZnlEQU1yNFkwLzVESDJrVUhUbUFLcUhOZXN1R0lq
            NFNSbFJOWnplbzVneWdVTzBya2I5Zm5MbVpWMk5zaVZtMG9GN3RCYVliUkNKWFFZ
            NStGV0NVS0hyb1piZDhqVXpsUFpYY21JRXI3ZXlkcUQwSURBKzZ0dWkxMDRVem9I
            N1IrRkdsUUNwYXV6ZzVXUE5aNit5YjExY1hxVkZtamJGRy9ZY052L1Q5a0krUEtX
            aURza2lianJEeHRNVklVTUR3ZXlWWlBzdm1GUDREZTRRVTF3Yk1iL0hSNDhrZUhV
            SmtnTTNBa2swbUpGU1h2UmNrckVmcHVoTFNIM29MQUdCaWZHaExHWEM3MDZqV3Ur
            N0I1Uko3RjBVbkphNDk3QmdteG9WNDZnTytqY1p4aWdpeTZTTkFla1lFb0lWQm9O
            ekIrWWI0eXRSblg4eVA2ZU1XWlNFWEVJZTBRYTMvUHpRYXNqdllHWFc0WHJNS3lE
            bE05d3dkcGRKWjczM21nQnp4UkN4Y2NtNFlIZmpkSHVkSDMyYXZFMUlsbm1Dc2Fu
            QU8zK3hpL0Z5SzdtYUVjRUltcWdlUnFlNDBneW1EQnRmNURiVnZCL29lOHB6ZXhq
            YXBCWHZFcW1FM2VZZG9hLzhOZ2s1R2N2U2NFNjh5OFV5cFF1N2JTQzZBaUdDMUxT
            OHlueXJHSXNLMVZXNnRERkN4NGxTTmJqMXJCa0haSUpldmVZRXRMUkFBWms2eTNX
            VHZjVnpHemZpNnl3SG1rdkNqRjd2bGFjM1NsSkxtbzVhTlVwOTdnNlNCeC9jQVNI
            SXVsWEp1VlRVL25ka1RKQ3RvV0xQdXdaRUNuL2V5Z0ZKd2EzOS9haFdWOVZVbGpU
            RHNCRmcwaVRHaEtkZW1ZcGVNSGE2OWcyOFVRcWlPdVdGQjlaNGoyeHhLL3V6enNy
            OUFIVWN3Q2FFejU5bU9VR3k5OUlRNXBNd2h1TmROS1BBMjU0Y0RBK3dhank3Q0pG
            NGxsditJSUt2aDVkMENtTzcvKzB0MlJZK2FsdWhuM1hBUFFzTXFnT05acnpEL080
            YjA3MWdSWUhocG1SdFZEemJ3dXNubkdxbklxQy9RcEQyTXJ1TVcyT2UzeHdld0Rv
            cjZjVzBIaFQxS28xSzA4OGVJWEN5SjhCZU1JMGRWSHplSGh1ZHBGYXlZNGxwRGtB
            YnhBSkJpWjdGbmlDdHRTSVRReFBrTlk0VlJsUUl5eFgzVjY2djdLVUYzcE9EVEV2
            UnJoVTErN3B1UUFBeUlwb1JWQ0kvaXpOK2pzUmVaVWtSRitBTWxsRS9mUGM1V3N6
            NDgvR012R1Y2QzBFMm1La05qT09DQmMvYjFwdkhkWitGQzFnVWRuVFpNeWlqditY
            R2xUU09QYWxUeVFWeUZ1b0RzVWs5L3B0N2twSjdRM29LYUwxMHA0MjduQ1VhQXdH
            U0I5bUwrTjV6TnlXUjBMZDE1Y09uTiswcmM4UGFsNVFwTlV4RkFERjlmWUQ5ZGw0
            ZSszeWRUOWJmNkhFbkhBVEZ1QlFNSlUvMWdCYlJDVllvQjQxZXZzL01BYkovQzRn
            dG5IdXk5TkVSZllwWENGcUp4UG84QklVdktDSXZoU2tIejk4Q1U3Ty82bnBpRW5X
            S2ZNR1BnOE81LzVoL0Y1WU1URTBGL0JtdGJObjBIcU5Ld21XY3VuTHVLSVN3bEEw
            V0ltL3J3Umh6WXBuaWJTZWR2Q0dmTWI2L3NOK1JUR1ZTMk54VnNXNmErQjhlZwpz
            ZUtjeDdWaDF6OE9EZ0cvcFdpR09HNm9JaHJseFlhQVVkbURLVmgvbjlJCi0tLSBN
            REtYYlFkdWxDR0ZkamJSRk9LMmF1cHArV25xdmt1UGFWSFplbk41YjFNCqs7/dSi
            ROXFExzs8x1CAadUr0963WdJzkvy/Vx0XDLpiuLW618BYGwaU91YDkn45QTs8oMX
            7f85WqYvyhZDKq4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:36:39Z"
    mac: ENC[AES256_GCM,data:1zrAWEDzFlCGc+pYCJz+dRQpMG2HMrkmM0bZ14r0R6J1i/PoSFa96hoaboz0Ldkgpd0GenxD/Al8nLr7PugzIXjRHef3HMob233V0LhstS4CPJ3qNQzSgISCw/e1Cx/ckbNXfpl8tRJCe2FU2eoCKVzmm8FJAGiQNrqUP7bNuvU=,iv:7aJvWziQjrx1qf4CGO6Txp4Ek3f3O6wRQpmMil15QjI=,tag:v691jME3SMd77CgkqOaK2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
