---
apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: ov-redis
spec:
  kubernetesConfig:
    image: quay.io/opstree/redis:v8.6.2
    imagePullPolicy: IfNotPresent
    redisSecret:
      name: redis-credentials
      key: password
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 256Mi
  storage:
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  redisExporter:
    enabled: false
    image: quay.io/opstree/redis-exporter:v1.82.0
