apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: ov
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:r+jzCiAZM2XzIfrEV7MTxUM19nPKNog=,iv:0v3xfbWSdyT3iakUhBZ1V1HAJxbfdPUxIj5rsKiQ0Wg=,tag:OWfjdgZkOMymvHo9zC+xtQ==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEN6UVJQOVNn
            TW9OaGgyb1k3Z21QcFNNTmNGZTJiT0lPYUZQem1oZjhiT25EWjdWQ0pWU2hRb3JF
            ZkR2ZmdLUmpIWGNibjNONmhuS2d6dnE1UDQ1eHB1SDNHcmVIQURzL1ZRMEVpQzBk
            Y0QrSkVRMEVnZi92OEZGUmw2VktnV3ZUNW5QOGNadnZ2dEFGOWE4ck1DSW5qYUlE
            K0lCQ2lBd3V6SGZHQVp2Z1JOQllhY0lQcEIySzJWVkQ1TDZoblZ5Uzc2VWN4Z05p
            UHVwRzl1NDlwV3c0by8vN3diOGpoVHAwZ0ttM1lOamhvOWdINWRLLzJWelFidFda
            YXlhR0JRaEVKZUt4TU5qTlR5VEhHdWVkS2llMlU0WUpJSnVCb085OVc4Q2l6d09N
            azg5TE1wZzF3bmlUTUh5OHFpWi9rNFh4V1BZZks4dis4a1pJQXRIY3phVkc4T3Ex
            OUpvTzlRTlR1QWhhSFkxYXpjaVVuVEYzTEROVFU4NjRvdTY0VmhUU04vZjhqTWR1
            QmJocGtEbmQ4THh0aWkxUTdKQTgyK1ZVK3JDcnhVUGo2STVHdStCMEtNc2k2T0Qr
            UDZJR3doTHhYMndNSUR3RVkwTVIzd1hHbTY2azVTVGhzOXBMYnJ6LzRLWkMyUGJq
            NVQvb1lpMzFOOGsvZ0dvblFGNlEwci9IZFo1MnluQ3BKRCtJcy9oZEhBWG0zUkF0
            UDEyb2E5VUVCeXdyNUxFdVhNREVFazlVT1lMM21QMVg3ZTkzREVyN2pZTTRaa3E3
            NUI4T1IwL2FKUDJjbTRXR2VLaVZPeFk1ZmVXWjl1QkVYVVhTeXpxN1d5R1BINFA3
            bmhESUROQTd1enROb2p1a085QkhjOU1WKzRMMGFWelA3VXhGc09zMWxWZzhsbGsr
            RjlGd2ZvVlZMZkhSeXp6dFBpYnExVnlMSVovVnBYaE9SM2FYUkQ4VXNMQXJQcnd0
            eVY1UHZHM1JnelFTRitzNWpoTVY2aWZzOGJ3bndhZE0vU2IxdXN2QmpVOHhERGJk
            MkF3Q1hjcDQzTmxBb2kzL1J5SldMbGRRbkU4VG9ZUGRxeEczdU16ZC9xbENBR0Ju
            TUJHb1VVSEpuTzNYUEg0Q092RG1MaGFnczN0Qk9HQUNMNE14c2NzTmhPRTRCL01x
            UUFCUkxmYnlMaURkLzFpOUpPVFludVNwSm5HSnJrZFJURklWTnR3WC9xaFJBdDIw
            bFlISWhRVEFJdXVZcHlHV0ZZK0I5Z1gzcERicVZhMnRqMi9hTG1vWmpTR1VWaWlh
            dXdydUhXZEw0Y0RpRVpuTldNS1pWcFZPS3cranhwbStlNXgzbjlJamhyUStUNDB1
            TXRSUXlxVFRnRVFwWVgrYmF5dU9xczVFQ09wQTR2SVZLR3FTcFF6RmtqUkVxRHo3
            ZFQ0NVNSRnltd0pzM0xXSmlSK0tVd3RRMDlla1ozQmlYclIwYUhxVk5xQzBQb3Zy
            VXBEWVdGYVZseW9BcUFGUVBZSkhjRGpRZVgvTi9DVHdwQ21rVG11OU9CdDNwRTg2
            VHMzY0VFUTh4Tjl3Uk03RUxRc2NzUlVwVGdLQ3RVSjd0T0tlbU1CbW83cWJkUHZo
            TVlKRG1FNnRDYWs2WWdibTlkRnNRUkNONmhCd0JYaHlqMjlzZk9Kd3hlOWlDVkc2
            cFBNNUpKbXAyTVdoRmQxN1VjSmhwZmNQN0w1YjQ3MkZUbXU0YjRoL1NoRWJtK0gr
            Q2NUcWs0VDBSbzIxUVJCa1dUcElqQkZxL2N0cktCTFpvNjNkRU56ZnNQMjN2dkR1
            OEVZNGgxQmQyVVBqQmt1Mlp2V3ROL2sya0xhYWNlRElES3RKSHROYmNPTGo2enND
            c1M4eUJkRlNtSUhLMHhDYkVlcWs5MG54N3RhVlBxZy9TNldOOUNBbitqMUxkNTRH
            ZGw2Qk9FM29vZE0xVVdhVzZYMXFSSGZDeGRraUpSSkhCdlJYUVFnVVNCYnpkdwp3
            VDhQMUhwV1NIL0pCNFFvd2pUcGtzcjFlQ2habEk2K0F5NUp2Q2pmWDdzCi0tLSA4
            YXJ2U0JoYjNaSktDVGZJbFVVVnhYU052ZTZ6UVc2MHhpS3lGemlhVDVBCqUtY5S5
            SBY7IVI0fa50d+BEl00ml3zhorw+3rnT4NvTZsxT+IgCx9OyvpG7mlTqZ172cAHr
            xvurh4bA1fBvdag=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T07:31:16Z"
    mac: ENC[AES256_GCM,data:bZ4uExLGMhqqiNqlo8bEhg/zGP7QBfGbYSaxgmPP9lIUu2tx3RA90ooDIV2CpAUUzV685RHJpQFLbmakynk8f4K94RQt2AFrFw1LtsBuGM0U4qaGDmFsFZX1ye7NdL3Ivri5Z5KU+H7CBNrYUwll0Ir8WHMsS4LPUvp4xMqIIQY=,iv:k/EG317Y1aCaI9X3d4sPevSeGWVgffvtvMc+F6IGelA=,tag:ej1Ld8qVSEDitxcAWZAQ+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
