apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-secret
    namespace: default
type: Opaque
stringData:
    vpn_pass: ENC[AES256_GCM,data:BBHbEoyOcS0=,iv:DwBGl8IJlTarAGR5TnNQO6XIMc3h5Clfum/WTByogeA=,tag:aBOVKWLhEEPz9J1sHrwNaA==,type:str]
    vpn_user: ENC[AES256_GCM,data:8AFgp7i/T0yLEej5iYpQ/8BgrZg=,iv:01dZ1hVYKN5ph7IdN8kmyUKHkdkM9DkE3iLbzCV4Zvg=,tag:HEX8U+djpZrP9nVfV8mx9g==,type:str]
sops:
    age:
        - recipient: age1pq1r9dyqput53j0dw3agxvs4xg2aqs9fp2x3n4s2h23pd7xad9jmvtrc3vgtz0wvkugq63z4s67puft98n3d3lafx9yca2s9eqq82spal5swmj9kcsyfs7fy7jt3wsmaw6z89zxjq52dy5knvm5tl9v73vypteln38aw24345az4mefwqeeelzhjasa5lrrfk4tqe33k8q84an79zpnzuysxdptt955xj4mq4gvpx5p3pj3n4ugv0vrkx3updx5yf3mpfscljvmxn3q35ztysnv0vc366nkhpgg8rstulaz2rs5yj28fz6rqwu56p3xw3ec9n4t03zc0jznxcdn6eavd80xj7ljxmhdfv4s6z699a7xswsjpe52nxcllvareg5n905f2lh80csk9gdgf3ua46dalttmrm9cgpldnzge0vhdldt7rqujt8uyja9ner7hqkptevyh4kdz5vc4dcv0h00s9q344cfxf8j42sfndhu320uq7stcxq3q2yd6xn45f3pvef2q0fh6fuf7sxtz30f3qkgqtrlpqd3dgyuwkacuw3dtxl9zgh98eq29875wme3hh3qn2cy7wzhu3w968crqh43maxyk4lrlvdu4ld2ltvmffyetsyt5x32l5fnc7u85u4p7aey5c8y4gca8qlklfnqyutz38g9g6g2svlq7hqpj764zvdzxrr5yrl78rd6nf2m26xuxf7vk0tt6wmfmknwjk469z9zq0ws3dws4th4fzkx3qnpvw2e04fk0v5kz27x3n8q6wtfcveqsthqjjcf970n8wrlyfyptyjk9a5gtjta5zjnfc69sc6uakd0vug7z9npz2eujzg3vw4cc33sc2rxqc9je46qqgwnrhfj8zurc0xq90t24prsjfw3akz5c2kyu8ufvn0p596wrp0875prgyzq2d9mgy8cfsvxfsy40rj3ggaxwfcxtmpgzawuuek0426qmhfn8sjsfhrqnsfahtshjydyny5858kzdgnas8h8r48skx8nmvk6kzvt893q59slqkdd6wxnw2xw3zcfkpqp4txfk2gg6n8p4cph7jx45gu9mz9f3eykaxn9p0t8tv36c3y5expp58fk3eyhsp3tl9u5jdczu4q4s2awmkdjpuk5tadt4fsv4924tvrfeyqu8pf0k7pymze9jc7mnk6wgj26m00yxq26xshuqa6py03ays9yuyz62xxmqchytt69zvg7vcjq4ugzxahp50gfye7zvghwmym4yejqeyjferanvy9le3ksszaewcat2kcg5gp4p2ezf36cmr2vh6ysztrrquauz7fq5n2d233w92s3kqgjl78m58m9r0rjr9wzjc3235szs4p9jv5r9hhexjr4ccka3a9w07m5rd6preex489hu7f3fwfyz489kn35ergzqtndgadmqd2atxds4s3vsrluz3skcvqvmqqpwhtc80d2rs8z0gq7eaddggxqyu6j9lht4vg3pc9l62aeps9nq5h5p6tzzc3pp5wwwyj0qfapp27r6xt0mp6j72tcnr3ta0mzgdc36hq8jwxya9farf2s5hyn8usmtxy9vgu4wjvyl8w9nndawwl5y8tsudteuwn097d6sl95k77dnspl6ek2k9gptc2usju29fsmk4cxz4thlwp6v9yv8qxkyscdklh3m9tz73rk657zt4vpzlevc537kt3x9q90rewyjrdjtydach8x25gq0rsam7w57npzs6aehmjp6w6hj4n9e6ktr63wt4gpzgs0gvycyzckrp3ue7yrvv7azgkk8tlhsh3avf3cf69tn0ntc26gy5y3xj0jalggvgm83kpv8kgeg7zg0g4r67g5ndnxm3xgluhqu5mhzpntlqpccdesnh2cpawuja52ledlacs9p0vv3za0jauzmy4h25yz6mlpm5t57w5r85mfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEVIWHlidlJF
            Rk9kdGtZdGYwZmVvUzVndGVpYWU4REJaTDRUQk9XQXhjeVY1OHVBYmNHWER0NjN2
            eWlwL3hkaUh1bldlTzgrbEdFQWF0Y0RLb2lNRUkwVm5zQWlLOHUyQnpBMHVZT2Zj
            MzM3S3E1VndLM3U5TENoUXF4WTFRaHQrWEtoTXY4OG9idkpCVWxBT0l0OS80aFBk
            akdEZzlSTEF2SWhVQmhaYnpidlBLNStYOGlXdmpUNWV1T284NG9uUzY0cFFCdmZx
            dTFVZ3VQTytRd3BNckZnTEx0bDB5VHNtOHVCV3daYUdKWElXQ3ZyWi9lWTNLVWVx
            Tm9WUUltR1EyZml0UGg3QkQ1RXlNZ25HRjNQZGdQZGxHeGRQVE0wakthQlhGVmJa
            RkpxTXB0ZkNxd2xKakdxdW1yVFJXbXczQnh4bFlLSkVYK0hsWXdWcG9iOWxEcjNo
            K0xXRlRIb3RiZkVpbTZQMEVWSlhDTCtUeGRucjlrV3l5d3U5N1ZoS3JKSC8zRDUx
            N3lGMDBzS3BRclR0YTBRWkdmM3FzTzloWUJXbFdKdVNTTjRUUExRSmE4elpGQ1dm
            RTNjRHM2bUFMZDlrWXM3dDZQbzl3WHJzNk14YkYzWEw2dUNNRWdzS0FLMWxBME9a
            RXlQN3pzU2NLMGFQUS9ZMjZmRm5VVmlVdnhzdmllN3N5ZEFVRFpueWFiVHZtNlNE
            TkRscHBwaytJMDFibzVmcjROQ2JIT0RGZXVocTBuMHRVTjUyWVJFclhrSUJnbVIw
            Nk1wc0VramZ4QVRpdDVxQWVNQ3dLTXMwYjcxcVp5a3hVbHhFTXZwQVdpZytGdVdY
            R1dEakwxZWJBYkxjaFVyL0dJUkZEZUFOVFR2Z0dCUUFibGJLQjEybjlqWlpQc2Ju
            UXZPaXVqdXdrc016UmlBaTM1YTJsS3h2cW9VVXpTcEQ5N1hPdFgwaEU4VGhhSlZn
            dkpNRzl2dGRQS2p4MXlhWms5TlJuUm9TVDN6dnJsNlh0ejF3ZFRVU05vamNFVTRL
            c1JtbXlMWHNHd3J5djJUTlRXU3BZUHVzZHhqZENMNUpBSldKeTY1UW9tOW55UEp0
            cTVqYld4Z3V0aTdMZHpWMTVLc0FrQWdXcUl2NHpKdWdtTEx1TW9zeDFuL05QNk5h
            L05MTmtSS28zSEFHbEUyVElWaWFlVjRhdXZpbEZza2k1N0d6K0xhWGlVMXJRQ0x3
            MkttK1VwRE9yL3FJdWROU1VxYzRNck4zZEhlU0NDQ05McHBzbmFUSjNYd3ZUSysv
            UGdiWXo2TmtydmF0RVNYZHNnbWhiMkU0QnlyZUdCblRoTS90TWt5SG5wVE41QTFL
            bTlLekFZSXBBcGRDTjhxUXM1VjVnZGlEWGN3YWx1S09GY1QrZW8ycFE2ckl3dm1N
            Sko1aU9GMVJzYjlnOGluQ1RhdlArZGZFMGM4cUNqTzNxcmhMZkg1eDNuMURhT2Qz
            clNaYlduMUlSZWRQWDJGVzNraWR3aTZ2YXRiak1CNytVUzB5K2ZSaU53NUNERWNv
            TjlpdzBPM2s0SHFyaytwdmxVNnUzMDFESFpYdy8xT3BTOFc4Wlp2aTZqbDFqbzg4
            V3BIWEZNT2xvTEw4dXNkdGVYdm9qSlcwREZvWWNBOUI4aUs3Qlp4KzJvTWVPWGU3
            Z1Q4cXNTb1F1T2E4QWdxZ2V0cVFVdDQ2a3Z1VzlUTG0vTXdCY1UvSjZJakhpNWdD
            SGJLaVBFSGZiQkNtMmxPR0JTMFlyYnhQV1R5eFFrUHZOUEVSMnozaUM3V01aNDdh
            MEFPWWxHVFAvcHZwVWJxRVB5OFBkSTd2dVJaakpZL3NPZVVFdmJmSlY2cXRWNmRX
            UkZWeFhoRDNPU09UeE5Wc3RvSXNMQmhJS01PMkpvbHQyTlBKZ1dLcEVDZFFkWW1m
            TUt5UEFEMlBYNndyc2VxNTZwdlZmaGdRTCtlYkt2MERMRGltRWZjNlNBN1NOZwp0
            NitnbkpDa0NMK3lQUWVXK1RlbkdhMFIySlFqMXFKcldDK1FjUWFwcmdZCi0tLSBl
            WUNlU0Y1aUVKSlBRWkFPellrV3BoUkE4dEZiM3gybXlrM2pTU0IyNXBBCi1c30oW
            pd8z4WkZsDi2mnaz3grjs3iw+C1bFiL22ttDYXCWRwxQgN+Q2VKk/bOdtXLjk2XI
            9BN2aglhcG6MIgQ=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T20:40:42Z"
    mac: ENC[AES256_GCM,data:Iaxl0llMXa0xm5HlNckWsPTogUiWigrD6gmqcOttei8m5VKZf+5t2P9M0Ac4kKBSLC74MoqVPpYZDl7gWVf0cLWwWiCJIREsyCHWPVxUWyAzLXsLDApBFhnm9DsIbi/yv1qxjPi2tMwRF1tCCV1/4J+Q6nPXkqdGo5afkvYqA04=,iv:bokrDCO2wPox0Y/B46NxEJVgsalEwxZm4eFLzBWd56k=,tag:oulXIyP7OkPconNwhX3ouA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
