apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-wireguard
    namespace: default
type: Opaque
stringData:
    wg0.conf: ENC[AES256_GCM,data:2wh06UWj70oLdc7GXQZ56LmexnHD2pIkQxm8Uqd1Up59Aubcv3AxSMllqTV6LUFBjisVLFkanIa7bQCtkGLIg9xAD3Tp+NjdzlilRfZgYNHr/nJNHHHW22PQCY5dWTSnIgWuCWiJqAHj6/MpGuFSCfPcpgAWxezmeLPlTw0yN//UAyvX9ZNbBkig9JqOaSdtURApDH8/GZwFpBLklX3QGL0AhOd87dZF8OncncWhKZv8PDJF05aoR2MJK+ecm9uSHz5RSAQxbfZijsFWvOTsHDq8jM8bEl9k8LLjKZrqFd+H78IyxSWbOSStGHx/l3FCMu24JKoVX3trIKNUBNGheTDazxUNSHh8GIlVVf3nDAgkDHry36j+1R8zBfXEKd+0YMEmm3s+7Pa08OYmT/5yitn8DvCDAlvClpbPiX9TVFsx5833mq8NiLZQL1HLGJCmmVwrtL5xXvE=,iv:Wre9U0RR5Shv3+jFsETBYlwjtWWCgCjLWAeiTRlhLxs=,tag:+v9mKSDWfaGb7/sm6Aiu1g==,type:str]
sops:
    age:
        - recipient: age1pq1r9dyqput53j0dw3agxvs4xg2aqs9fp2x3n4s2h23pd7xad9jmvtrc3vgtz0wvkugq63z4s67puft98n3d3lafx9yca2s9eqq82spal5swmj9kcsyfs7fy7jt3wsmaw6z89zxjq52dy5knvm5tl9v73vypteln38aw24345az4mefwqeeelzhjasa5lrrfk4tqe33k8q84an79zpnzuysxdptt955xj4mq4gvpx5p3pj3n4ugv0vrkx3updx5yf3mpfscljvmxn3q35ztysnv0vc366nkhpgg8rstulaz2rs5yj28fz6rqwu56p3xw3ec9n4t03zc0jznxcdn6eavd80xj7ljxmhdfv4s6z699a7xswsjpe52nxcllvareg5n905f2lh80csk9gdgf3ua46dalttmrm9cgpldnzge0vhdldt7rqujt8uyja9ner7hqkptevyh4kdz5vc4dcv0h00s9q344cfxf8j42sfndhu320uq7stcxq3q2yd6xn45f3pvef2q0fh6fuf7sxtz30f3qkgqtrlpqd3dgyuwkacuw3dtxl9zgh98eq29875wme3hh3qn2cy7wzhu3w968crqh43maxyk4lrlvdu4ld2ltvmffyetsyt5x32l5fnc7u85u4p7aey5c8y4gca8qlklfnqyutz38g9g6g2svlq7hqpj764zvdzxrr5yrl78rd6nf2m26xuxf7vk0tt6wmfmknwjk469z9zq0ws3dws4th4fzkx3qnpvw2e04fk0v5kz27x3n8q6wtfcveqsthqjjcf970n8wrlyfyptyjk9a5gtjta5zjnfc69sc6uakd0vug7z9npz2eujzg3vw4cc33sc2rxqc9je46qqgwnrhfj8zurc0xq90t24prsjfw3akz5c2kyu8ufvn0p596wrp0875prgyzq2d9mgy8cfsvxfsy40rj3ggaxwfcxtmpgzawuuek0426qmhfn8sjsfhrqnsfahtshjydyny5858kzdgnas8h8r48skx8nmvk6kzvt893q59slqkdd6wxnw2xw3zcfkpqp4txfk2gg6n8p4cph7jx45gu9mz9f3eykaxn9p0t8tv36c3y5expp58fk3eyhsp3tl9u5jdczu4q4s2awmkdjpuk5tadt4fsv4924tvrfeyqu8pf0k7pymze9jc7mnk6wgj26m00yxq26xshuqa6py03ays9yuyz62xxmqchytt69zvg7vcjq4ugzxahp50gfye7zvghwmym4yejqeyjferanvy9le3ksszaewcat2kcg5gp4p2ezf36cmr2vh6ysztrrquauz7fq5n2d233w92s3kqgjl78m58m9r0rjr9wzjc3235szs4p9jv5r9hhexjr4ccka3a9w07m5rd6preex489hu7f3fwfyz489kn35ergzqtndgadmqd2atxds4s3vsrluz3skcvqvmqqpwhtc80d2rs8z0gq7eaddggxqyu6j9lht4vg3pc9l62aeps9nq5h5p6tzzc3pp5wwwyj0qfapp27r6xt0mp6j72tcnr3ta0mzgdc36hq8jwxya9farf2s5hyn8usmtxy9vgu4wjvyl8w9nndawwl5y8tsudteuwn097d6sl95k77dnspl6ek2k9gptc2usju29fsmk4cxz4thlwp6v9yv8qxkyscdklh3m9tz73rk657zt4vpzlevc537kt3x9q90rewyjrdjtydach8x25gq0rsam7w57npzs6aehmjp6w6hj4n9e6ktr63wt4gpzgs0gvycyzckrp3ue7yrvv7azgkk8tlhsh3avf3cf69tn0ntc26gy5y3xj0jalggvgm83kpv8kgeg7zg0g4r67g5ndnxm3xgluhqu5mhzpntlqpccdesnh2cpawuja52ledlacs9p0vv3za0jauzmy4h25yz6mlpm5t57w5r85mfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGxRU0ZjUU56
            UzZFazJtbGVKWDc3SEhYdFJIRjBUZXZzSXJyRHViUHhXSS9MMlRZRXdoNkN3WHhZ
            bkVZejJIdk84T0RhamdqekEzOWJRdDMrOTNFVlFZUDlrMW1GZHczQVVmY1RReWtm
            VjZjdEdCNGdaYkJiaDRvajZmVDJwL3l5QUVyRUF6VWVBUm1EQTduUkM1WmE4NVhK
            TWxxanFNV3pEaURaNm5ySGlveEtEMU00SW80VkFQanlZanlBTHB3QWhxQlN1K3ZO
            M0VGUUd6ODJvS3Ztc2l2MjZ3RjBqc0tTK0Q1cEFHb1kzR3BIb2hKSHkwQWV6bjVt
            TSthUklVOHFPRjVrdTZoR3FtWE9Ra0o5VlhXN253VjN2K0xKMzZtcjN1VVZaUG5x
            cGVrYTVwT0dNUWo3TWRNRVRoTVNqZWNobXhTdFkwSFI4c3RReGlGc2JsWHBKV25s
            Z3FjbzhLbkg0VmZNZFpmRzBoaFpuVjNVNWtUY0d3Und1eXNVZk9ibjkxQTJQWDZU
            eXpwaTVUZmRyT2dOUjdFME90dFNheU5mcTAvOW5HZUVIYzZtd1h4SWwvYWVqR0dp
            dG9LRXQxTGtLNHFqK0s1NzhhWEx2UGR0RzRpYjlzUkgwUEtDMnNQUDJmRU5leU9H
            bjloNzFwWEtxRzZURGovYmZzSGtZU0VGUWFhT1lzUFF2eWd0WXFhWCtqUnp5d1Ri
            NnZtUWpTa3ZlODgzTy9xSUZ3clVya0U1cmoySGhSNWRKWkQ1SmJLYXY1d3VHKzRR
            SG5CR0M1bjY5OG1wcFB4eGZLY2FBMjN5SUgrUUlMdllaK2tUdnBHN0RQOW5WVGh0
            aUN2U1dCZi9OZ2tzK3JFVGMxSW5xYVFNaTlNckx3a3h1RHF2akEvL3NIN1JDelM5
            SWJpMUQ5ZDVQR0JQT2Y1emNYUmZqR244d1VseTZqaFN3VnpHNGJ2Y01VbGhwOCtY
            ZWZKV3ZQeUx1QzhUZUFENWtiSVpGZGl1SU1wZ0I0NnhaeVRkU3pMOEp4ZkNXNThp
            NEkwSk5RWVc2RDVlaGtWWmgwK1ZkV2YvZUpWenh6cW1ybjYzQzhxRHExSDc4ZmFW
            S0Y3UXg4eVZRUEJZYklEQll4K2lPejNVdFVVNmh6ZnhXTnBybXM5NXI3YmxoMUpU
            eGViZU1PZ3hBNEJhWWZtd3VoYkhEMVFEWFVsVWRIZTl2eXpxeXJWWkZJOTJrcE5j
            OG81TmNBSUpvMitHdU51Y2tlOCtsMk44RG5GN3kzYnRTWllobWNsMyszRzAvVzkw
            SU5kdUMxc2ZlS291ZnBTZVppd1NQZDdKZWdaaTZ0eS9aaFdPM2t6blNyN1Y4ZFVn
            NElUZHlPVkVsS2Y3UkRsTnl1UGtPdEwwVG5ZL2lrVVdnL0U4RDBmbjI3K2ZteldW
            VWkxOTFHOTZPYm9ZaGwzWncrVzBIZGhjZkVPc1lDZjNZTldpajBiM056N3Z2eTkv
            REl2ZWNHWjFlNitQVFhuWEFZbWVhT0ZFd1I5MTBXcUpMWldQYTU5T2U3RFBwWndj
            RGVzQzVGVGl5NFVJSHUyZDE1V0psSFYvakMwM0twNEt1R0pEcVMyVk93SWZlQXBU
            TzMvNUJjQUh1Njg0VXN4UWpoWE9qNGRFaElURXRZZHpjY1FyelNwNDV5T2hMMFBN
            djFuRjhJMVZTL0I2OTdyS0pJYkFlUFhEcGg3VTRQME1PS0hKelA5Nk8xc0thTGpJ
            MW9HWTNsTE4wbDlvYUNjVXNHRVlQK3hiNmRiSXNKWlczWjFRRkhRWU5OY3M3RkxF
            eTlMRW5oY1Z1bEtrZllURkxtMFJ5UGFMTG5rVW9WN2VGbHI2U05kL2FjK2ZkMDk5
            dUU2YTdCbUJqZm9sUnh5T2ppL1ozVkpHU3NvY1BQZjh5cU11amEvM3VTdkpvZ3Nt
            WDRXQkNab25EUTdkdnhJRURLSVhIb1drZHZqUjBtRkVhTXdyRVF5YndzZXZaQQpF
            RGN5ZW1wMEdlc1JPWEdHaU12ZDR2SDh3eUhkY2FtMjRVc3M3dWdmWjFBCi0tLSBF
            bUJSSG56QXlOZ0ludGYra0s4TzJzMnNkT1Y1RkI3Q0d3Q2hhRWxqZ0dnCqnm3nQK
            OT9mTYBpbFVbHmb5ZbaURTDs23f0TrQuQk9mlJOr5AcpaYiznYvuDTfg+A7ZdyMd
            MIkX8lV2Y9FXnOs=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-13T20:40:42Z"
    mac: ENC[AES256_GCM,data:FPVeNz3Eqq6xoxBF72He4Ca5It7Wnd3ELfKRW/l/YRp8vITBSHI0tyCayonOinGhh7FlMAKb165g8CDn3wdrDXKS1E+HtZgG8tDal95B5rKXGui7Oh2yWIi0SmRe80JXbUm+0WMbV11OHGVd3MqN7TWOiPZjtCxj6Uay+0OGF88=,iv:HNynMo7hnDVOTEExRN8sdflfhc26M/zDp/2ovdWoPog=,tag:AfUVGRuC8RC7GFqAEe/bNw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
