# source: https://github.com/obeone/charts/blob/main/charts/technitium-dnsserver/values.yaml

image:
  repository: technitium/dns-server
  tag: latest@sha256:3580381de00ba316748abced1ad0f942aff5a625993fa5dee22a902e26d2c524 # 14.3.0

persistence:
  config:
    enabled: true
    storageClass: local-storage
    size: 10Gi
    mountPath: /etc/dns
