# source: https://github.com/obeone/charts/blob/main/charts/technitium-dnsserver/values.yaml

image:
  repository: technitium/dns-server
  tag: latest@sha256:60d258760304e22d5dad362f487aa3c3f2e04b97b24467cbfa1caa402f096ecf # 14.3.0

persistence:
  config:
    enabled: true
    storageClass: local-storage
    size: 10Gi
    mountPath: /etc/dns
