apiVersion: v1
kind: Secret
metadata:
    name: backup-rustfs-credentials
    namespace: temporal
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:YAlL7jiWMjPj+qmCG+YVjHccZSk=,iv:qGicblztgeICpJJcolUBM64KqmL4d6Lmq5fYDmZHHzQ=,tag:osvn1L2GNBBB6pNQrV+VAg==,type:str]
    secret-key: ENC[AES256_GCM,data:CqPkQA4BCM+h3WjRTyu9SyT5K0mPLhsKRYcwV0YwhOjijAFIA8m4iMXrHms=,iv:MLoyUGY0H5N5Yfroim9DxmjoEar3UEpXj2l5C2UWGvw=,tag:nJcMuuuE/PTyYLRvHZo0/w==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGE3NEJ0QlpD
            ellDb2d4TEwycmJXSWxKdWFDa05yN0N4K1d5eVZsTkJEUHRXbzg2aTFVN0owSlFJ
            WkJaNDFKUTQ3S0k0MGluUHNsSmdHRENQUlg1UjArMnNZQ3o4MzhLQ2Jhalk0UExz
            RTFnMlE5aCtMcFdSMkt3UWxmOEM1N3lsV2xpam1FNXc5cWFremhCbnVLRkJIckhB
            OGZ0TGNSaFhLT1kwbnN6TTNoMW9NVWdxQmFac0lDUm1ITmtpNStMWFhOcE5DZDgr
            YlJML3gzbVMyQUh0QytUd0dCNklFcHM1cWczOUxwaVJRekRkZGFYbzU4NjBrb3Ev
            UU5QajcvendDWE1Kam1VYWhCNmJYVHZRWWptYThUYTB4amFYd0FucFhZUWk2T3Nj
            TTVhbDRnMnZWUTkySFlHZ1l2OTNDaW9KR01WNmVMWWdkdS92azM5UUxBTWp3S1M0
            b1QvbHkybmZ6ZDU3OXJjbytQREErTUZvQVFrOEpWajBCY09UZEVUNnFHZW5VY0Rt
            blVySFo3bVUxVll2dWVaaCs0WHZwa29IM0pDWEYrL0VFZXJPbXd0RGRPWE5vTzdL
            VEFCWFdCNkdvcWEvREMzK0RjRkhBSG1HellVbmp4T2x3aXpNNzZBVmtwS3ErYUtE
            UHQ1SEhLQ0Y0eGNsbFZNY0ZLT1Vac0V1RmNuaFQxbzBlSUsxRFJUaDMzM1dNS01Z
            VW5CY3ZINFVWclM3N241TE1GSUMxdVgyMHF0T2ZNMnpkNWJTUisxa1VoNDJnWGl3
            d0h5UHptRkM3c1AwYTNUYTcyUUpueW00dWJXQWZVWW1MSUdUcXVlOTZIUndrdGNn
            RFEzSjU0SVMyVmRPWG0xTVZaNFgwRXdVRklMckk5Q1dBbVFvSVlNSmsxam1rV0kx
            Y1pienRyY0piZi9FMEFIY3Foa1RJL0RZcmhKVUFuWTl2SUJLVnhPeGJsNDJ1Y2Iz
            UXhUcjE5OXJnaHpjN1hza0lqUko4bFAwYzQrdXhSV3lsenY5aTRDTVRVNWZJSjZh
            UlhPQi8yTFNpbS9VYnZ4RVBnSXVJcUp6Y2lhVXlIR25XVnlvbHpqMkU0M2tZMC8x
            TW1XWmtudnZvSHNTdUQ2LzNpbllKK0M3QjVySzZrMlM4NnJSbDFaSTFHZ3NsY1A3
            K0ZORzIxNHJLajF0eEZjZDVNWVdwSGc1c25wZTJtVGprQk41VXVVbm9GOEszUUgy
            N1BNNkRabERjSGpkVUczaEduYVcva0pGdHcvRWhQRFQ1cXBVaTd2dnBtOU1EYks2
            bmJ1ZS9NMytNK2I3Qms3VWp4d1dFekI4cUVPWVFhdGlEQm5qelRiQk03T1FkTm55
            T0s1Z0Y5bHUvRkkzWkhKYUs2NFVxZjlLWldaemR2aTVLSFY3YzhRR3ZLVnJoMXVB
            RFVSTUJodkNVQ2c0cEZja1loOVJlTTM1YUNPSUtlUzJObldEWUxVOWdZbDNya2J4
            UkhQYzBKUTFheERQR2ZUeDFTekRJZ0tVWnE4UmRJUHJudUtJZlQydG5lbTV2RlJH
            cGFDbkMyeXBNNFJFampKL1IwQW5IejhyT0R2UzFHdUQ1MVUvRU5UbW8xbmVkNzg4
            eWtPUFJmaFIweXg3Y3RqcXlLNzlaa1cwVWp3dStVZmQ5ZjdyNnlIc2ljdVVpZFpt
            TlVIaGpQVnRSWnlVQ1paK0ZaYkwzbGFHZyt3SVZtbFdhcEZXZEd1bFpxME4zOWND
            S1lXVTZZNFZpMEExM1hjRU8zd08wOFF0S05RS0dhYVByMHVhbjZ0UFhKWE9laGhq
            V0RZS2wxeWxEM0ViUnMwSU93VzZjR1BMMmV6YXViNVJwQTYxMW1Gajlva3UrZ1Mx
            eHdaSlJlNGE2cHI3bEtvM2NpNlZESnJ3aHV3aWN6R3VQZnRBaGdMQnFITU00alRY
            RnhXdlc5U3lHYjF3Szg0c0YrbGZoSURBTmthY3pTQnBVbFVSMVVFekQ1bEFMUQpu
            citQc1NiMlJYMVcramtxa0lEQVhzZzU5SzNiSnJMalVobm5PYk5FM3Y4Ci0tLSB4
            bE5wNmZwNExYck1EUk5HcnZpRVYycWNPR2V6S1duVlh4VG5ZVTcxUmdzCp1fgJmC
            fU87DVU9w4Coo/ZZZVhpJc6byxthWrQ/z7fzSSNy2i46fd3uIQ7kJJfw1aE+R7oP
            FdneEi98ZMYH9V0=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:38:47Z"
    mac: ENC[AES256_GCM,data:Fd+V6pw7AF7sIk1fIR30G12l6g5PlnX5oGS+mYqt+6GYhwEa5F82UgYwf6Iy7Z+peHFywZPtxZwCy6ZMHAM6uNJTg4GB8k2tGynJuNknYr/JIH9ijV5tF267CRVb7ToDz7paeZkdDxVDwxx6tQGGrRIWvp/WMcXoAMSQPBgj3RQ=,iv:nVfABscY/gFEr0MmoqThBSwYfj33I7DbBk20Vj5UVhk=,tag:2z3hbdy0/01JyIBgrfYOVQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
