apiVersion: v1
kind: Secret
metadata:
    name: temporal-postgres-credentials
    namespace: temporal
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:0uELi5PDBcE=,iv:8IhazIbWQwG3i4tqwL4RiWFwUduCRYpzpKXsRo9v2d8=,tag:FgMu5Mi8dfGUceHMx2Isyg==,type:str]
    password: ENC[AES256_GCM,data:L5Twle4scuE2vDpUrSNsGaDwpGP1vQ==,iv:cGXam4G4S5fDAE8vCSSdKMp74yUx/f3nA0QdlcOTXy0=,tag:IyqqpWNMLgUEXHuYbcuy/A==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDVQSE1NL2Yx
            K2FoUlNPR2xoTFBhc0UyR3BoTEpxSHZUeUdiMVdlQ1dtSGx0UWIyTU1KZnliN2ZY
            d0I0aE5ocVBsbGN3bGQ0R2lwRjB2OENHMzljVENyRkRva0NlNnhJbHVsYlJ3WURQ
            U2hwUHI1K1hSMFpPRkVKelFwOXhVdlQwT0VXeGtweGpMYkVvNmFIakUzZVliajM4
            VEo4WXJPbGZ1MVYyeDlveWhLY3BqdldqRUkxb3RCWDZwQ1dwWllBNk9WcjBIR2VG
            TXVqYVR1NCtBaE96S0VkTHE0ZUE4cGlJSTJKcVp5VTlpOE8zZ2RwWmc3MDlpbk9D
            QzI4eWFWRU9pR2Y2Y1grSTQ4MWgwWkpDakhuWDFqOG9Db1lHSWxLZGY1YS84NzFs
            c3V4c0ZtRElHa082aWlocmNLODhYL0tyM2lBVUNXN3MyZVhXYmQ4NmZlbUtXQTlE
            cDkxRHJOU1F1eFgxeHJUNk03VVhNMGJDV1doNGpoN0xGRkZWRUlKY3RJSTYzSFVI
            R0xFM3ptZi92WFI4SlMrTGtpTjJrVWV4N25IWENiNHhHL3B1OEtxTkdqd0JLeTg3
            c09RMFp5cW5MTXdhYkJBVTJsTmsvUFhYdHkrUzJIeTArZ0pTcWozWlR5SElwSmhl
            NTJJbG92ZWUwQ2lIYy9SajFMdWowZjNSZlFlOVZjay9oc0tCbDJJNlA3K1NmdVhI
            bTQ0VllHdWNta3g0TURjYWVJK2d0N2F0Q3hhUUR4OTF2Z0pmREx2RTcwUFdHcDM1
            b2ZyRTMwVDZUOUFTZ28vbnp1UmQ2Z3ZtVG12cHVhUmYzL3hNR3RsdWFKWTlCdzRB
            amI5REtDWUZUSHRCV0hOcWpkN3FCQy8zdlNGa1hSelRWUWMxTEJ4TUJEaXlxdnAz
            TmVuM2Q2QkkxY0JhSDBIWXV2czREM0s5YkNOR1hIWUhKeCtSYkNyQUZtQ01lTktV
            elg4TnRHbDF5STdvdWMxa09ROFZ5YnVJOVZwb2dPOE85OVJmZnhmOUFJZGZnbDV4
            ZmF1bGxwdmdwQnJvQjYvSzc4bHo2K2JEdEpGR3lDU2ZJLzdRYVRWTjdZUWZ0eXg0
            TnhaV3dOSmxvN01kK3o5NnNBMXJMNm9hSUhKTWVYQ2JST1RMTDVwMlZadVVYMm5x
            bm1Ec2xsYXlxNG4yaFgyV1JMNWdhUEJzKzJTN082ekVLem5KUXNPQThTNzZSS1Z4
            ZWorbGRkM3p6TmhNaWoxcnlmUlUxZ2g3TkhQT29GZ2tkanlyNWxlL0FNWSs4UmN6
            dlJtS0loZytoZkhDemVvR2pXTFNhdVNUYTM2MGFyMlNFYVdHUnpiTTl0QjRac1Ix
            MGQ0ZWpBMXNSWGNiam1OV2FyMGtCc2d3THNqSzJydlBVSGhiWjBpdEJMandOenR0
            NmI2UU5RS2oxVDkySlVOUGNMd0FXazh1VmZncW9kdklHek9mU3VjZU15NXRVUlRI
            TlZSZkRQeTNQYlRWc3hJeUlDZUhyL0Nsay8wMVUyZEFKVWZ0eE9TRjJmUTZsalEx
            V29UMDJsZXo0dmJhNzlqTHV3M0taQ1ZHV3N4WW5UYVVXalFTN1d0bWw2eEY2T0gx
            ZVAvRURzbVE1Q2oxa05rWkxFQ0NxZEdFNmo1d1JiL0lLKzVVd3VHa2x5U3o2S1hY
            TTQwWE5nZlEreUVNWXl6Ry9mUlBQMDVGREZTUzdSN3JsWkdyOFlOODI5MUFhOCtz
            VW5HOGV6OUxGbjRkSnkvd1oxaVltT2NiVXBDR3Z4WSsvTVN5aWd4cTJ4d0p4Y1lM
            WmZTdXJjUyt1NGlSRjZJdHUxd3liNWw4UTExanRETjlWdkxkUU56RG9obnNnYjBr
            UlcwaDU5NjlCaVFkOW1hNHMzOVhHUkI4Q0YzRlB6T3RiUmpqalFyeFkxNUxaaUVW
            ZWdIMWNQZHAvbFJSNVdFVnJzcjZzaTFiS2lGejVLKzFJOVN6VmxGZFNxcGZMUQp0
            aXdxN3p5MUt5N1pQTnZBeEhxdFVRNFh1SlBoR2thSmVXUmZvWXJJREZrCi0tLSBC
            SFNVNEF6TTVyYWhZVW91YktteDdQRURycGtpOUFzUmcxV2thY2hwV1BzChu9JgGo
            2/p30Cr8r98G/hvpUUOdsEih7FBhiKnq0HzDhBa2eDjBMwyB3aVWbUXaX1MZ1Vuj
            hukYtDAKGntc5wg=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T03:35:42Z"
    mac: ENC[AES256_GCM,data:Wxm37iFNVUjp+Ovnf4FXHX3ffq2tIsdBcxdqSjyYMQP2zIn2mfEzF3jMG7pwM2G+DB7FN19O21DhbmkFHnlPud5q60Zm+7ugCanId083QeHROch/Up7xrQk6vXIKdiQb6dfr/X9pVQnHjgxHLl0QQ6cAKqF+CDfxvrM0Pspe50Q=,iv:xBJXKTqqUgkY2XDwWVUvcBlaqzLylqzYR2enaTPYVK0=,tag:12yammrs6ixHKVASN3wadQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
