apiVersion: v1
kind: Secret
metadata:
    name: temporal-postgres-credentials
    namespace: ov
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:4jzSoIMLNOU=,iv:Kd2LgqjaK7BF7Nii9rF8X25c4i0MYauV1QEvnrFhWuw=,tag:DsdU5UM5BnRpgIbWB/2UgA==,type:str]
    password: ENC[AES256_GCM,data:06M2ggE0HeDvWLzdTKYZ/+vYZODJ5w==,iv:xsp3rRpWLHprNd703yfLmrfvXWOXrEt+cyOALHTnozg=,tag:bKV9CxpYN9GDk5ESHM9clw==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHFlSWxWazZ0
            WnBESzlnZEFlUU9Yei9xcHIzMWpFVUY1cXBTNGNaazFZNmlCWENZNnpOZGdYeFdP
            alZrdUhwZXlkWml4YmVGT1FZNjNsaEhMbElMNGFlaFdQZDFOQ2hBSE9VSWNlYVhV
            SS9hdXNOMWs0UVdKbmhJQmUxUGUzdVRuOUJTWDNTZm9YbVFjY0NwNUJlUDJoUElY
            azRmRUV2aTBITVk0OExhWFdMRndnUFlreHBnMTFpdmgranRubDVVVzgwekZ4bWIx
            am54TUlwRUwyNUhtakUrTkxZQVdnSnd4RXlEZGluczBsVHo5Vk5rT29IdXBjV2tk
            Q3JKT1VVYnpYeVNtaFVPV3dJN1l6WVRmUlJ1WVdMcnpEbFRpenRwQ1BaNmYzbWk3
            QzMyNTl5dkIvOFNxbDdrUy9GWGJrNlhjdHIzQ0NpNFpxYndzaWFtL1FDdFRvcEpD
            V0grVnF6TkRUUE96Q2tkakY0T2tpNC9VSnBKRkE2V3RFS1JqZ1AvbktydEluVkxP
            bzRtK1VYMGpHUHdmSzRSNkxYSGdKbWhQb3Y4dEFRbFdNVXEwSHljMDU0NWpTSTk0
            bWxRYnlrSVBCNnE2R05vRmVQc2RQS3JrZE9UNzVDRURrSGcvTktpL0tPOXdpQmhR
            M0xweWtFY1pOb0UxQTVoaFNjTTJjUmhOUzd3UTUycDlMNXZ1MHB4TWxmQ1JqQjc4
            YzFIc0lOZ2ZGVGhrcmNvUVpiQnVoVE1kYjFrYitXbGlRamowUzlyajNBeUNaRjhV
            elBmZjMrT25EcGVwZTRtTTgzMFZkYWFuNHhRNEd2S0RFcklOb29NTVF4TWlhMzlK
            WlcrTVM1MWN2MFNGTS9qOVRJMWRNWmliSHg1clBHSUVPNFI5UERoTGJQRGxuWllD
            Yk5hQXkzUlJDT3lvSHozTWNhUXhYSzlhdE1LZ2QwT3UzWHM1ZDZrUG5JMnR5djJj
            VkNYdDE5dlRIMnAzUjRkSUo0bTdERzlXV0FLMlJIbFV5eDZmWm9ISWVQQ1c1YjIz
            OTgwaVppeHRYY3QrSnlpWEd4TEFRbG84WC9ndEtGUkV4dGpHQVBhbDRtQWpNRC9h
            a1dxY3JNVS93dWRPT2ZZZDNVdjhXQXlaY0FTMWpQTjZRcStFQUFtWkJsWE1nMzN5
            WkJJRmV1dC9sY1M3dFEwME9tUzNjQUxDS0k2aDFVQzJWdXJrRlFWc2Y4aDNhNUth
            UktGV1BzS2t3VSt4Q3FHQkJlM0Mza25VbFpxSmVoOHJFN0NPVjRtQTl3NzM3NFBR
            eDBrc1BWM3d4MkQvd3pyOGFaZTVlaGxwRzYwNXRiYk82RkpaTklEVE94QTI5bm5t
            bkRCamVQMGFCRkJuWG1tRDNQOEljNzZlTVFaQmdpS2NuRTZlaFhXeEtWUEdDVTA4
            ZXUvWFRLeGZ4bDNTaStzVVBBZ1pPOHgzMDdqcUFxS2U3SkVnN2NpZllWdURtR3d3
            QlgwQWVtMlQ1QURPdUxJaEM4VzNEWFFEZDB6TmdxT3BmVWtzWDNFREtqbmN2S1hh
            K3NVRHJpVnRxL2lwQTdsM1ZhbC83cXhXRENaanlidUlLejNVTWpJWjg0eTJDUzhi
            cFp4L05sWXBlQ3VEallsUVVpUW8wd05ScXFCbDNxUVduY0VFdDVzNCtXRmRDZUVj
            UytmdE1jVktMT28wWjB3bG9CbFhKK09TVThGNDZLN2FQV1JhQm1PR0FVaWFQcEdj
            Q2ViT1VPVTBwM1VFSHlNbnQzSmZQc2ZKemxHZnZZWGVncHI2RHJ4aVZ6RDFFQXZn
            eW8rR1YvZlhxamhKbkhHRHVLeitEZFJtc0NJaU5iUElkZk15ekFOWFBkNndrQUhz
            S0xseVA3VUJXZ2pScjczQ0xFUWlYZHRMcGFYZkxYV2xzNUFXcC9NeklqendNZGJJ
            ZWQ3V0FvLzV1ekMrclUrZEpXeGY2M3Z4OXVheGtiVEVhZWYyeXJpTGxFWGZaZwpN
            UVNUQUZBWm1IZHo5UWNpYml3NklhNnd3OUVsSDN5T1dEckFDU2ZBK2ZFCi0tLSBI
            Y05BNk01ZUN5L01jdE9yY1BEQlZoNXVDaW0vRnFZOVZLbkZGdlErZjhZCsbgCaSt
            w/ny3sEB1661ZjPmZ2WTrIoS9G5KTEbaw1TgkuEdIeedWUN+zNmxt9/WOavWlcxa
            oekHUJQzDj6n1iw=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T00:06:04Z"
    mac: ENC[AES256_GCM,data:uiAEZJP08dcthr7qz4NsgxVcmM9lOOoRGshg4MSSdaIWV8KLbfqTSvqE2i6/17x8rV0p4YD5nKg1bNDhvH6X6QSrsUlcMMfVSY4oeivNdHamqMMVDdnL5I1h6oaPv91AFDc0HsUZbWkmkwx7/D7VTKeQpN1pvtt7k94ntZDD5i4=,iv:yQFBHZDYGr2c5VF7SyJi6EH1ryGye1/OIe/umvCpNTQ=,tag:pHrY3ig4fuojX+norqmkgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
