# https://github.com/pajikos/home-assistant-helm-chart/tree/main/charts/home-assistant

ingress:
  enabled: true
  className: traefik-internal
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt-packet-fail
    external-dns.alpha.kubernetes.io/hostname: ha.packet.fail
  hosts:
  - host: ha.packet.fail
    paths:
    - path: /
      pathType: ImplementationSpecific
      backend:
        service:
          name: home-assistant
          port:
            number: 8080
  tls:
  - secretName: home-assistant-tls
    hosts:
    - ha.packet.fail
resources:
  limits:
    akri.sh/zigbee: '1'
  requests:
    akri.sh/zigbee: '1'
configuration:
  enabled: true
  forceInit: true
persistence:
  enabled: true
  storageClass: local-path
