# source: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

grafana:
  initChownData:
    enabled: false
  securityContext:
    fsGroup: 472
    runAsUser: 472
    runAsGroup: 472
  adminUser: admin
  admin:
    existingSecret: grafana-admin-credentials
    userKey: admin-user
    passwordKey: admin-password
  persistence:
    enabled: true
    storageClassName: local-path
    size: 2Gi
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 512Mi
  ingress:
    enabled: true
    ingressClassName: traefik-internal
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt-packet-fail
      external-dns.alpha.kubernetes.io/hostname: grafana-nuc01.packet.fail
    hosts:
      - grafana-nuc01.packet.fail
    tls:
      - secretName: grafana-nuc01-tls
        hosts:
          - grafana-nuc01.packet.fail
  additionalDataSources:
    - name: Tempo
      type: tempo
      uid: tempo
      url: http://tempo.monitoring.svc.cluster.local:3100
      access: proxy
      isDefault: false
      jsonData:
        tracesToMetricsEnabled: true
        tracesToMetrics:
          datasourceUid: prometheus
  sidecar:
    dashboards:
      enabled: true
    datasources:
      enabled: true

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
    retention: 15d
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1536Mi
    enableRemoteWriteReceiver: true
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: local-path
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

prometheusOperator:
  admissionWebhooks:
    patch:
      enabled: false
    certManager:
      enabled: true
      issuerRef:
        name: selfsigned
        kind: ClusterIssuer
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
