---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Charg/home.git
    path: kube/nuc01/cloudflared
    targetRevision: main
    plugin: {}
  destination:
    namespace: cloudflared
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: monitoring.coreos.com
      kind: PodMonitor
      jqPathExpressions:
        - .spec.podMetricsEndpoints[].relabelings[].action
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
