---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Charg/home.git
    path: kube/nuc01/accord
    targetRevision: main
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
