apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: ac
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:dvYZig1q7OCbaGfX1Vv2N8hyEek=,iv:W750Oxj4ib05Rh1p4HVxZxd6qxrxjaEx5BU2w+vX3z4=,tag:cTTb6PIySN+3XaKcRI2/Tw==,type:str]
    secret-key: ENC[AES256_GCM,data:MD8j5xi6Xj8ofTNb9ONfzUU4A7VWuzVhqRRcqf4QHea6a1+f0zbPKJvy+oX/ni1hS/XJEObWCnA=,iv:Y/mxITeMcM2LOxexHchW/sFSj07w4UtqkvZ3ChhOGdM=,tag:mItNXxYgwCmdmRzC4VxtDQ==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE03dWx2Umt1
            MkE4TGZDRjM4UG9KWk5Kck5TdXpZRW5XcWNnSEFtMWVzc05STDVCeDdYU1JKOTY1
            eHFwaFlmODRZRXFtcTJMbituRktwdWtHeFVWY3RQdWRXc1pEaHZRM3orN25IQTlY
            RnppcUc1KzZJVTQ4Q01HNVBiUVhvR3dWYUZGWU03S3pTQ0s5cHZLLzhzSFVScUR6
            UzM5akxaQVBvZ0RvOVZCY3dWWkxNTXRRM0s5NmoxS25ZL29Zakk2bkZUcFVEdWln
            NDVOWFp2djQ4UlIwSjExTDIxZmNGMWFTZVNvK2NpcDJEeXlFVU12TVVLS01zZ3NI
            MlZxcFdTZ21udGErZXlJRGVzWCtmMW1JR3VBV2xCWFBsN2FMemJBTXo2M3BmSTE2
            S2RJVGYrMDRFeTUxeXpIZHAvQklRcnhpL2xQTEhSY2d5SnI4MHM5eUhNTzYyeW1U
            RTVtWFNROWtOZHBvSmkreFl2MnR1UjZZOUNONDQzdHNnSWYzSVBRWHBaTWhQNjBk
            bzdBbnVqalVVK3dtZml1UXVZeVgzWEt2RGVKZ1pBRFR5VDQ5aWlqMGJRVkUzZnFq
            K1hVbzdOd1grN1RBN0xDSUcwc1VSTUExMUhqL251aDFiaE9UQ1RhTEh3YkV4aXR4
            d2dzZGduQkdmU3pMZE9OcFpOQkwwNHJUVFR6bTVWbjlmVUZFVFl3bTZOYlhmeWZj
            aDdVZWo3b2xQUEJFQ0FaNFFqM0U0Y0xYSmJQa3U0cVFabnlKdmlxazBweWQ2RkhS
            TnFSS3gyOUV2TTNWMUs2a2l3U2p3OEtpT1pHdUVpMEh1WjRkT1VobW82K2s1ZmZR
            TmtnTjdyQ2ZqYUJpaDU0VVpBaGJNUHpxZExxVmpWMWVlbnRPbnBCZVAySlhudWp1
            SjBRZnNTM2ZUWVFDaVdpVmMrRTR6LytxLzljZ3dPdEVzc0tEWVVnTVFVY2dGSVNI
            Sy9vWGpSeDVWR3h6elAyZWFMRWVCUmtlbmxlN1FQU2F2cmUzVXFUR0R6WFpxa2Zv
            ejVLUzd1K2NuUEhkUDlSeXVhMGlydmJMam5lVE1kcGpCMC9TRk5DMTRNakJTSXBF
            VlRxajVNVjdueDBCSm5XUWdQM3JoUFQ5eS8wV3NMSUh3K002RVkrMitiRGkrK0FR
            Wjh1aXlFYXNGOWlod1NRR2t5c2hxdTAzYVpoVFNWR0F0Yk55QU1wWllOM2FQeXln
            QkxKZExuYTRUclJFQ09jY09aNllqd1VtYldTTjVrQ0ZBbjV2TXV3Wi96VkkvTVBj
            TG96b1Uwd3pBMXY0dVpsUjF6MjBTZUxBWGRPV0F2QXY4WXFWaTdualhYVXh0ajVy
            clFPMy9jMkxZSFBYdU1xK1JueFlVREtGWjRTMDZaMklBZlpGdGc2dzZqRjNHOGNp
            ckFjVkY3UFNlTUpJbU0ycHBSSkhuUzU4RVhkUHFaeHNoUDBWd3ZHU0NqZlEzNlIv
            aDhuU2tOZWdlV0dySW05Q2xGbkpRdUNVSlg0c1kvZTk5K1BCRE1VWGFJUDg2TG1U
            NzBzdHNmaUZkVkNXOVBwTEgrb0ZXQlV1S1prOC9uWGl2cW5zWjZId1FmcEVpUjA4
            Ukt3RGp1ZSs5bHhScW5JQkVuVmx2ME1iKzVTamY2NTdueUdQdWdDc0Z3ekpvRkhx
            ZXg0SG5weE1wQVdzOEZraXhwMHFnZm8zVHZ4ZFB2eXo5QWljaERnck10T2E3MUVJ
            ZHByL3lkb3BlaWNVdWM3YjFmcS9hb2NrSStyUFFYOUZ5WEovdHAxb3NuT2o0VWZM
            ZHMzRlU1Z0NnU2hjQ0x3U2UxNWV1Uzg1YWkwN0E5OHAwcnE0dmZCclNJTi8rWXgy
            STBnMngrbDFma2lUdWUrWUNrSXRxSUhWOVk3VURJUkJISUpwa0xTR3o4eGtuQ0hW
            MTlFSDFFaHJNYjl5SHp0MTdSUm1JL1ZMWDZ5dTdHTWpXMC9DL2xrT2RSdlNEUQpl
            UlRwZVE2RlRvR1FYc2dEaDhaWE13ZTVuRDQ1dkY3ZGZTZklCZTNvSDRvCi0tLSBO
            SEZyYVN2cVZmYVFNSW9mbDBNNmduTzZna29zVDNabmVYQlVUZlladkN3Cg7l1uWH
            ae9QGiePzUvsOVll9OLRd4QL6NoWDx6CzMgAKB7hiN40GdEkgHv5vhnr1RZnmoW1
            ex22YylFW275WDU=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T05:49:32Z"
    mac: ENC[AES256_GCM,data:5szJ9GcUkf2UPqhbJZMDm0k+Jbpn1C1jCyj0U8x09JKwp6P3VxZtwTbT4hJ0ficK2QqbcE7sTgJAOLJdZAXtVBj9BB6RwO0B6J0iN5vyG0bM0spWWwAqyPb6jNHG9Cm22f1kT/Ocv125avUPkzBBB32qMPid9ZoreEVChKH1yus=,iv:YcKBu/NVaoud+eAeygo/NTpE8/m1yxb6Z4hddLKE23o=,tag:iUo7OLc2AeAwbopHM6Uv1g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
