# source: https://github.com/SynologyOpenSource/synology-csi/tree/main/deploy/helm
clientInfoSecret:
  create: false
  name: client-info-secret

storageClasses:
  synology-iscsi-storage:
    reclaimPolicy: Retain
    parameters:
      fsType: ext4
      formatOptions: "-E nodiscard"
