apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:RSZ9r8U=,iv:7wIQFRdAIGYGd857MWxfD4OXFdBdtONIfzfvJ12ssLY=,tag:t1uWlQ/m8e0PARRHL31r8Q==,type:str]
    admin-password: ENC[AES256_GCM,data:XSGGQstNSF2zLQG8LeYdV83ng1QDOyXXmPIbg7w77cQ=,iv:0jmDtQpCAXVqJeYnx8iBnHGRNKyx5jchlk42l4pr7r8=,tag:7UNTmZdvkA/Y/nTAyF+9FQ==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDVzancvU3No
            anlPQmhPQW15UTBhdVFURWY5VzhwTEFLeFpjeUdHMzRLZFJGR2sxSFpBRDN2ZmxS
            NTJMbkdCVC9pL0NWNkx4WlZUOUdCMHF1T3o3bDJqRUh0QlVVYkFMMG9rNVdHTXJT
            SVFIdVc1a0ZTeXlpcXNYTm90LzdyUjFmU2tBV1czU0NzeXk2cXozYTI3WmlMQlNY
            Ti9TWXpjY2MycXNuKzc1VjRmZ2pOK2ZMVWNvRUpBWDZZZ1hzS3JsTUZKc3FyZkRj
            bVplK1QwQXMrVGk3d0ZrVnJKK0FROFgvSFpmbWE2YmtIN1VvY2F1dG1IVHl0UWpr
            WHluSkZXL0RHS2FpWnpWSmtGaFpnUENoWVhvdDJRaWdjaEo4Mkt5TVJoLzBpSnBC
            Uy8zb0hBWFM1a3NKVzRabTN0eVRaWmFGMXpPRVNqaVpqaHZtQnZ6bi9EVHcvTVpy
            T2laY2thaXVyM0V5dlBhK2QzWTJDbVovK1NTMGo2R2dXWW50NlpwUW9rMVJaaDV5
            NzdaWHFlZXVIS2lHbjNMejVWU01GYjlCS2dabDVHNEJvWEhMUzlmTFg3RGkweEJV
            SXhqdlhCdzBQdmozZFRKSUtKVmxzbHl0Ty9ZOGxLcUN6VkpzQ1BJbFlnejJjd1BY
            UXEwdkxTbnk3QVlHRVUvQk04VHJ3N0E0a3dBT2VGbDVocTJPTmorbDR1RjVyek1k
            d25HUDJ2d00zb2VJcWMvSkdzckdpQTdTMTA0SG9LZUp4VVhXbkE3NjltTXVNLzFp
            VXZmVVhRQ2FHU2xGTVBJMnp5TkdzQkZORzZJQ09qQWR2MFc5dllOY2o5Q0JmTWg2
            Zm1EN2RsbFpMdjlUZHE1NEdTYnB0NXBycXJuaEpOWkR6Yk9sZXRrd2ZhcU9ZR3ZE
            dWRGV29QYnZ5djhSeDRlek56YUY4T0MxUHNaekZXejNnUDNEQ3JUYzlSTi9ma2RW
            QUFCT29lRWRZZDNpTDRNelVjSVcvQy9tVjdyM0VSTUZwL2hGWUNuTHJQVk40UXVK
            MkZuYTBPRm5tb3dmTWxGL0w1dWVPSHlwQitJU2hPK3M0V2hUZloxL2xYb3lFTDY3
            UFN3REs4bm9kMGxOc1RzQ2tkQy9qQzQzV3c5YXJiVFZjR1UxMmJGckNIcUEzNlhq
            R1hmNkJKcTVtZ0J2YU9XdEdTZmlaL1FZckhhVUlWYzM5SE0xSDg3cGdJeHRZWUkv
            MzArd3B5eVpYRjZ5N1ZXNXV3QWdZZ2YrNWZZZ3pLeXhEb3Iza2NUejhKOEwyN1Fl
            MUFJRjBNNHZhei8zNlpOTXpXZzZLNG1peUU5bnh2L1U1UUFEWkRHajlubVVwa2lY
            N2VhNGk0eEhDd3RMb2pUbWQ0U0xUTmUreGM2WjkwVVB1SXhhMGZXRE9SUmJMMmVp
            b01oQ29UU01OemR3RUJkQzFybUIvNUc2YUd2THRmZ0luaGFURnZUNGFJSkE4R2pB
            aXNvUEZCSzBxNDM3Zys2czZkMm16WDVrSTNjd0M3cHlHOENobDhnc21tbzNrTTFI
            ODlDeEMwMzJiaXplVDZYMVZ4U1ZlTFJVZ0xMWlU5RElBZmRlemFSMDJUMWtSeWpF
            ZEpaSWFVdjJNRkREaGt0cHYwTGFGakQrZlQwUDNadWxFNE5zazVyc2xFRGVSZm5R
            eU1mNVFmZmw2UmxlSTEwRlFDYlpEb3ptTTJmUFY3Q3Bsb3EwOWxNR0dQMkR2M2tB
            dlZMTEdFUDJDbDFZaDhobS92Y3Y2L2JmYXB1TzRmUCtYWTVhN0V6YUM1Q1puYkZ0
            WlBCSXh6eWl0SmdIUFJ3Y0J6d043TGVSUDkzRVdxTGpGTmlYU3pHOTNXRUMremVy
            aVp1akwrUFVVL0M4TjdWVENRWUhGemQ0MG9tZUJuWE0rQ0NjZ2dQc0hUTmd3em5r
            MFFTZEptMGZIdkcvYURydFBnRHJDajhISlR5QkZWODJDaU5FR3VoUW1STnBYdwp0
            SUozRktUaGEvb2tCM2dlZHJEcytYbXpBbXdTMXUxejB6eFI4U2lrb3M0Ci0tLSBr
            QVMyZ0NHUDZKNDEwa0FVVFJuWGczOWduMENNYWVsdXpiNE5MVDYzWUFFCh2v9SJ3
            RnTKZc9wFqvHXpSX0uJ5cmS+sfrPI3HjRE/xZKrLomrvsojW5ucyf4apruHjwsk8
            G3Od9FssDe6qL0w=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T02:20:25Z"
    mac: ENC[AES256_GCM,data:ERdg5/MfxFuhfl/i33aSuYZJBE+Q8RHhp10SXQachARWbEOKQ1hdmkDLXB71o5MFtaMLvTPJrNtK3BmBo2QTzcM0oB8/9oXrcp8AqqYkCsgPs83ONrjYPhoVfMBFXLpX6eJeYXWaNQUOJqIBPYD8gwT3ElBvK8Fsggx31D1hudk=,iv:Jhruw4ZMqIVw4rPzyy6/vIdcS29md8hKKGVB0Azn3KQ=,tag:wNS8Ppn/Bq2Qq3i+InMTAQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
