---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord-worker
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: ghcr.io/charg/charts
    chart: accord
    targetRevision: 0.3.0
    helm:
      valuesObject:
        image:
          tag: 0.3.0
        imagePullSecrets:
          - name: ghcr-pull-creds
        existingSecret: accord-env
        migrations:
          enabled: false
        web:
          enabled: false
        worker:
          enabled: true
          replicaAcount: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
  destination:
    namespace: ac
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
