---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord-web
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: ghcr.io/charg/charts
    chart: accord
    targetRevision: 0.2.0
    helm:
      valuesObject:
        image:
          tag: 0.2.0
        imagePullSecrets:
          - name: ghcr-pull-creds
        existingSecret: accord-env
        migrations:
          enabled: false
        worker:
          enabled: false
        web:
          enabled: true
        ingress:
          enabled: true
          className: traefik-internal
          annotations:
            cert-manager.io/cluster-issuer: lets-encrypt-packet-fail
            external-dns.alpha.kubernetes.io/hostname: accord-nuc01.packet.fail
          hosts:
            - host: accord-nuc01.packet.fail
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: accord-nuc01-tls
              hosts:
                - accord-nuc01.packet.fail
  destination:
    namespace: ac
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
