---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: accord-migrations
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: ghcr.io/charg/charts
    chart: accord
    targetRevision: 0.2.1
    helm:
      valuesObject:
        image:
          tag: 0.2.1
        imagePullSecrets:
          - name: ghcr-pull-creds
        existingSecret: accord-env
        web:
          enabled: false
        worker:
          enabled: false
        migrations:
          enabled: true
          runId: 0.2.1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
  destination:
    namespace: ac
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
