image:
  tag: latest
  pullPolicy: Always
ingress:
  enabled: true
  ingressClassName: traefik-public
  url: https://plex.syn.sh
  tls:
  - hosts:
    - plex.syn.sh
    secretName: tls-plex-ingress
pms:
  storageClassName: synology-iscsi-storage
  configStorage: 10Gi
  resources:
    requests:
      cpu: 1000m
      memory: 2Gi
      gpu.intel.com/i915: '1'
    limits:
      gpu.intel.com/i915: '1'
      cpu: 6000m
      memory: 22Gi
extraEnv:
  HOSTNAME: plex.packet.fail
extraVolumeMounts:
- name: plex-media
  mountPath: /media
- name: plex-transcode
  mountPath: /transcode_custom
extraVolumes:
- name: plex-media
  persistentVolumeClaim:
    claimName: plex-media
- name: plex-transcode
  emptyDir:
    medium: Memory
    sizeLimit: 20Gi
