apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-api-key
    namespace: default
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:ZkUUqk1tjyp/G5dsvV1GVAY60S8JjOxmZhL7HWSznqM=,iv:slVnIjwg0pudVderMOJfluqyBRwwpvLhsRJhLvQJMhI=,tag:Wc/0+poNDckgragQ2dTfoQ==,type:str]
sops:
    age:
        - recipient: age1pq1r9dyqput53j0dw3agxvs4xg2aqs9fp2x3n4s2h23pd7xad9jmvtrc3vgtz0wvkugq63z4s67puft98n3d3lafx9yca2s9eqq82spal5swmj9kcsyfs7fy7jt3wsmaw6z89zxjq52dy5knvm5tl9v73vypteln38aw24345az4mefwqeeelzhjasa5lrrfk4tqe33k8q84an79zpnzuysxdptt955xj4mq4gvpx5p3pj3n4ugv0vrkx3updx5yf3mpfscljvmxn3q35ztysnv0vc366nkhpgg8rstulaz2rs5yj28fz6rqwu56p3xw3ec9n4t03zc0jznxcdn6eavd80xj7ljxmhdfv4s6z699a7xswsjpe52nxcllvareg5n905f2lh80csk9gdgf3ua46dalttmrm9cgpldnzge0vhdldt7rqujt8uyja9ner7hqkptevyh4kdz5vc4dcv0h00s9q344cfxf8j42sfndhu320uq7stcxq3q2yd6xn45f3pvef2q0fh6fuf7sxtz30f3qkgqtrlpqd3dgyuwkacuw3dtxl9zgh98eq29875wme3hh3qn2cy7wzhu3w968crqh43maxyk4lrlvdu4ld2ltvmffyetsyt5x32l5fnc7u85u4p7aey5c8y4gca8qlklfnqyutz38g9g6g2svlq7hqpj764zvdzxrr5yrl78rd6nf2m26xuxf7vk0tt6wmfmknwjk469z9zq0ws3dws4th4fzkx3qnpvw2e04fk0v5kz27x3n8q6wtfcveqsthqjjcf970n8wrlyfyptyjk9a5gtjta5zjnfc69sc6uakd0vug7z9npz2eujzg3vw4cc33sc2rxqc9je46qqgwnrhfj8zurc0xq90t24prsjfw3akz5c2kyu8ufvn0p596wrp0875prgyzq2d9mgy8cfsvxfsy40rj3ggaxwfcxtmpgzawuuek0426qmhfn8sjsfhrqnsfahtshjydyny5858kzdgnas8h8r48skx8nmvk6kzvt893q59slqkdd6wxnw2xw3zcfkpqp4txfk2gg6n8p4cph7jx45gu9mz9f3eykaxn9p0t8tv36c3y5expp58fk3eyhsp3tl9u5jdczu4q4s2awmkdjpuk5tadt4fsv4924tvrfeyqu8pf0k7pymze9jc7mnk6wgj26m00yxq26xshuqa6py03ays9yuyz62xxmqchytt69zvg7vcjq4ugzxahp50gfye7zvghwmym4yejqeyjferanvy9le3ksszaewcat2kcg5gp4p2ezf36cmr2vh6ysztrrquauz7fq5n2d233w92s3kqgjl78m58m9r0rjr9wzjc3235szs4p9jv5r9hhexjr4ccka3a9w07m5rd6preex489hu7f3fwfyz489kn35ergzqtndgadmqd2atxds4s3vsrluz3skcvqvmqqpwhtc80d2rs8z0gq7eaddggxqyu6j9lht4vg3pc9l62aeps9nq5h5p6tzzc3pp5wwwyj0qfapp27r6xt0mp6j72tcnr3ta0mzgdc36hq8jwxya9farf2s5hyn8usmtxy9vgu4wjvyl8w9nndawwl5y8tsudteuwn097d6sl95k77dnspl6ek2k9gptc2usju29fsmk4cxz4thlwp6v9yv8qxkyscdklh3m9tz73rk657zt4vpzlevc537kt3x9q90rewyjrdjtydach8x25gq0rsam7w57npzs6aehmjp6w6hj4n9e6ktr63wt4gpzgs0gvycyzckrp3ue7yrvv7azgkk8tlhsh3avf3cf69tn0ntc26gy5y3xj0jalggvgm83kpv8kgeg7zg0g4r67g5ndnxm3xgluhqu5mhzpntlqpccdesnh2cpawuja52ledlacs9p0vv3za0jauzmy4h25yz6mlpm5t57w5r85mfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IERnWlVGZEta
            ZktNN3AwUUdEMU5VTW02MXRlc0FTTS9XZ0VpK0dFNHFVM2FJRWJNVmJzOVRmZjZP
            OHZTbnNBNTdoWFZJcTRSYkF2eTd5TnNqemNvTElWZi9JNXN1aUtncWZHbENNY0lG
            eElNcmNneXZteUswUmNxMzRSTzB5aWVlS3hhckV2dktzNURKZ29lbG5VVE1HYzN6
            dUNnMFpEbEh1WFlybWExbkxScTY4ajhBMjFOM0J6RkRFV3NFMlFqMWZoUnZKckpC
            K2syMUtROXB6MlJ6SDZGUEVsai9XV011Z2xnWEJsMElKMzgvT3NhN1l1MnMzVHYz
            c2haamZiakxqeVhFSWdCVlN6RGttYnpQcTlvd21UNnVlekM4YWRxVGExMktkMFpM
            ZFcyQXZ0WWs3Rk54bmZIOGkvWUYzSmRzWXRITURBQUtXNEFkaG1JN0QyZG9QNW9u
            bExBdDBac2dibkorWGpxb1FaZWJmMUlkQW9KRVM4aWtRb2FOVGx1bGhNZTAzdnUv
            aTJTdXhsa2hpbE9TTjZTNUYzZTFFTVM5clY3azFHSXg2dFdBdW01Q2RNYzdUUldB
            MFJGQm40VXFGaVBSWnRKK2tPNncvNTMveEw1UlBaTnhHdUdSemVQSGNYUGZrRGdW
            RWhPWC9KSzRsMzlWODBEWDVxYndBYmpXTUFDRnJDV1cwOXJQY2lKdnhwY3dybkxs
            YVdId01XRjY4WmVzMTVtQzBJQnRBZjlMQkFSNXF3NkFtdHBMc3p3bVU0bkVEUDQr
            YzkvRDRuY3lXRXUrWHRIWVpJUTArMHVndXlZZWpKSmUweW1PYUFkMXBZWGFYQmhR
            Vi9kZVkvZUl1OVp5dWZ0Y1ZaTW9tOFJRRWxHUUh1RjVPMUtyS1BGcWxDMWtEYzJK
            bEl4bzN4cjhOWXFBb3cvUnZiTjJqV1FiOVFMSFNvQkZXcXNRMTNkc2tyYTE4bmxK
            SlpxeXhWRjNvenhPQmhQN09xbS9VRWczWUluZG8zdWhPZEEwenIwVjdHTkdHR2tS
            RzltUTVLNEF4R0F6a1dGREpvTm1OVzdVclE0emxxenR6MFE4ZkJlR2JuUzdDcC84
            Q3ZiRC9sVDYwUXpkeWpqVmRxUk5PTzRxZ0dvaEY0dndKYXNhcG55UmloaDBWYkxs
            NURKM2d5dm5lNmNwM0pkcHVEeWhVY1d4OTlqUXZxbWhvMTB4eDhTQVNBNUNLZHpm
            enY4alVkSVhveWxtTVVqNVJiZGlyOHVNOUppZDBvVHNrQmFsSjFhMmZtYXhJZGtj
            UUttM29XK3FjSlpnUzJGRUV4UHBGSXhWMUszbzdHMW1ZTUJHc1c5bVN5ZVI0cmk3
            MzlaalhJV0tvUzdOL0xnM3I1V0FXSXZnTDR0Z2F4UU5SeFBYd1NmM3YvelJTL2NH
            ZFJQMlEwVGxDS1dBdzJoRFFVWFMrdTZaZ1lBOW5JMmJ2NDY0T1dMd0IxUFNZRXJl
            YmtjL2FyWGF4emtBUGhvMXNPb2xDYWtvVXAxU0xBNGxhVU9uTE03d2VtdGtmM0lH
            Z1pBR2hFeXdzbE1VMGxrVWFoZGhLcVJIcVNpazR0ZjZ6dndPQ3QzQUEvN2xTS1hk
            NzFMTFR3N3BMTktXMDZ6MlgrRHlnSzlyMGhPUEEzcEl2SFFLaFFUaWZFeXRlclkr
            MFZvb0c2Qmo1cTZPSWFhU0c3UW9HWURkbHVMWU5CRkdaK2hBVlhCQ3o5UDJVM0FU
            RXFReS9LQUZERFhoMGhocWtxdk5HZGtnYjZQUU1wNFNKNjdTNWRvak9WMnhNSWUx
            c1NMcmQ2eVJENjVDZVE0N09IVnhkTFExT20xWnE2N1kxU1VremVobldhUU5lT210
            cW1ObU9RYW55S0JTa1BINGxxV085VWRQOHEyWDlZRUVSVlo2OCtadDBudkFEUGZm
            bFcxV2VyanUrNnk5bFZDRE9KLzIxVlcrR0dXVDF6R1dNMUZnNzVFR2VhU25iUQpO
            dVZ5OU5mTHJPanN2d3NDcjZyb3BBbXZJSUQ5UEx2ZmRST1Zmc1didlA4Ci0tLSAy
            VllvOVcyYm81NDdqbFNXK2gxeVp5VmtncEYxOGR5Q2NRelFqZ1AyQkdRCjl9fevQ
            +c0iyS4kh+RGgX0V9+jPT11wezUGIu1+YuJwhljyV6TIvV9+PlzLkDxB64w7aynY
            jeR5la3v6p/TXrw=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-14T22:12:15Z"
    mac: ENC[AES256_GCM,data:vCJ7qfoFF2oVtnnWrbIaN/c3j4iu+Sv2ZyxbuWQM3Bx3847wSn9zLd0sS+FfYKfW12IhJTnvfYccOfHy0RBeVKHdhsOdRq1ZMO4kbbohEbC2XL+3Tx/HsXOBJuNX+gRuKPd0w1ZUFrM0Dko0Re3M6z/Ld0yJXN/ioeNE2M78nTs=,iv:v/sDKisUYgRQoQQN8nytefUcYWXKf/kAq8by8VOyvW8=,tag:gXUy06VxSqWgxJ2IJoW7PQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
