apiVersion: v1
kind: Secret
metadata:
    name: rustfs-credentials
    namespace: ov
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:l+L94Q3pZJw+mmeaa+QpjF4vkHs=,iv:jiWwxAvcFQ8xhftKfwxUmS6wJMU7kBgdU+V+EyKqHes=,tag:DaMd5woB+3X2+hYPHYSTvA==,type:str]
    secret-key: ENC[AES256_GCM,data:MXfK4RvCwDpKZLbKai1yt4cpKYpZJ4cjeXHPAeDldfF+Fl3VRab50w==,iv:xobfbL9hCNvneCG1qODJWTW4cQto5635XtM5+/WPlPs=,tag:Z+WN1rzOi8EqTaIZVEFdtw==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHVvYWxuRnBz
            d0pVbFpXbEZ1T3BlNFdHNDYzS0FvM2xxZCtoZVRaQnpoKzRmUFJ6bUpzZ3pZZUhF
            eWx6Ky90NUlBYWtaSzJjZGhjNjliaFJrMzdpVUpaREp2TlAxOXRYM1NwS2MwVGdK
            NUFFbjRmTC9QclluTXFTS1JkUWszZlBGUVNmOGNPUVRNR09SVUwxZnl0MHlRa2JB
            MTdmNTI0djQ5UXpOZUsxOWo1elY2b002Yko3NlcxUjRFaTFYT1ZkaW1UME4rajdl
            SjErRTQrZTBlVlRwOWZDTjA1RXZjZWdBR2ZDeG83QU43bkZ6bThMVzd5TmJBWVNx
            SzhVeE4rclkyWVFWa3NmZmdwcWdYcm5kbTY1ZWdTVDYwWWQ4U09EZU5aSG5TOHQ5
            Y1lhMnpGZWVCelkrekxHUDZJV1QwS0xwMTJybjJLem5ldE91SGZYUTYrbjNFa0U0
            ZndtRjZpOHVDQUU5R29vd084K1k0NzJmQy9Ec3V0NHo5WE41S3NkMjhUanBKWVFU
            VWVsTG5lbGVQK2NQSmNPZm9YbERmYW5pTnI0cFNXZ2xBOTlQRThzek9KR0c0OWo2
            d0d1VjlDL3JXNU1hNE8yeTQ1RGpVS1FTK01ESlg4UlErNTZ1UzZCd2pkMWJsT003
            d1BhK3JINkVrN2tGZFo4YzlXQkJrVUVZTUdYeDlxMjltWHlmUm1Hb0tDOTNUc2x0
            Q0hoalV4dFVYME5ITFJ1TkhndE1xL25QKzJaeUg1bGhqKy9mZGdFSm9UeVJra1BU
            QmtndXJrdStEK2dsdnNEbk0rMDV4MGtVOXBTTWZabStBK0dJMGZ3cU5iUlE2alEx
            RURKN2wxYnpocC90d3AvajNITDhKb0VWMTgvdTI5bDlsdUZ0NndRSUxOQXhyYXRw
            U0RNamJLcVhLNmxmQjhLby9yY3ZsU2piY0lQczdJN1N4aVRrTmkxZ0lvVFFPejZI
            SjAraEpZR2YvKzBOOTRKWDB6NVNJR05TYTNYeE1ReTJ3bEU4SjZvblZNci94MnIv
            eDkzcitzNU9wN2JqYmg0OU9lOXFrcHFtUllNR2ErT1A4QW9HY2xqb2dpQVNXQjV2
            ZTJXRXBwYUpVSW1GM2RPODhqUWNIWnNpTm1QVUVjbmcxRktFby9IR1YwRDkxS2FU
            U1JtUmo2L2JiZTNKNWtvSnE5WVNJb1lHQkt6SVBXN25wV0I0YUN1Qk9BU2hnVnZx
            UDRadHpYbytBeG1aNk42N1hncWI0Mkc1Uktpdis4eHFSM01nQmFicHk5dXFjODR0
            QmhYWHRtMzlIWlhwbVIvYnVRUk8rckJ0NFZKU2RSL1FhYU1zR3YzcE1IMHVidUxK
            ZXRiK3BCV0Q0MGNDMHVER0ZVaG9HWUQxZHd1ZkFHWkFadFdiQmhnNElNVzNKZG94
            YzRNRWxZV0JkNGVaaTFnRGR0UU1sd2dQSXU2RGRuQVNMbEFLSTJqMDFZMG1LRThq
            RlZ2VFAxU1l6UVlnYVZCaEFRbEtjZklxNFcvT1NMTEs0QmlSSjNjZlRjS0pMdE9K
            aDJWZndwNmhENzNSM3RFaGxoenZqL0NqWTdBNHNla2Q0TVdXR3hmb3B2NWJ6bk0y
            TkZ4OHV2VzhZbkg2dlIrYWVkamJMOHNXV1RJS2lqaFE1Ri9SOVZkeGpkVWx3NFVR
            cVBIMU5hVTlQcTFUNjVaMTFodG8wYXFPejFsY3VwQnpGUW9GWndEYlB5THlWdjBh
            VDFCaStXZ1FlcFNsZ1NOWk9kWXNkNWJpRUc2Z0NKTlYrcDRscWpsV3Vxa09Ma1Nh
            WXBWTzBUckNmeEJDVnU4czJRWSszTDZUTnhPSkQ2ZnRmNUFBeXVaR3dtSE5lUWNP
            bCtsdzFPUWdMUzRKMFNtT05obVFwejVYSDdDaTNITWxIalZCbVNCRHZSVWtmYTFo
            QWZrNENRQ2F3QjNRc3NGSmRZVjhSY29kOUhXM2N0cGd2SnkzSHE0YkpmWlZCQQpK
            ZXNuc3gyVW9rZjZOazRCVmxyRTJoSDNZa3RCcTFXMndLR0tTa1pNUktVCi0tLSA2
            anhnMm9LNU8vYjEvNnN2RTBhVXlsYkxtK3lxWDljUXN3OXpmcHZCRDl3CmwxbY+0
            rFopAvqpD6qAlOEs4rP8MqAC41uh/rVBh7r98YzeWmpC5Y9IHUe77mza6Xs3qkZ1
            aA3L0nJ4GbGaf7Q=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-28T07:03:28Z"
    mac: ENC[AES256_GCM,data:fWmsLBMHcj/E0wGzqg8QgfidoDKCkmfyE7ToTHP8RvKMenzXTwHNAqXBXyza1CMFeDc/+Hcf6Y/G7sYD0BVD5woQTaUDEsZtaxeeMZSypN2d/ju5TuuMm7w4qgQwR2jCdFM7HMS1DSykpKKhq/vgJAe5Q58bsUuNJTJMpvohDOs=,iv:hmNCqMU8dH94ZmiH5C0Bh2e3ZILUGB6ploeghwKFzWM=,tag:uacfQDBzrPw1BvjBME//7w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
