# source: https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml

ingressClass:
  enabled: true
  isDefaultClass: true
  name: traefik-internal

providers:
  kubernetesCRD:
    enabled: true
    ingressClass: traefik-internal
  kubernetesIngress:
    enabled: true
    ingressClass: traefik-internal

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 300m
    memory: 256Mi

ingressRoute:
  dashboard:
    enabled: true
