---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ov-postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-minimal-trixie
  instances: 1

  bootstrap:
    initdb:
      owner: veto
      secret:
        name: postgres-credentials

  postgresql:
    extensions:
    - name: pgvector
      image:
        # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector
        reference: ghcr.io/cloudnative-pg/pgvector:0.8.2-18-trixie

  storage:
    size: 100Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
