---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ov-postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 1

  bootstrap:
    initdb:
      owner: veto
      secret:
        name: postgres-credentials

  storage:
    size: 100Gi

  monitoring:
    enablePodMonitor: true
    customQueriesConfigMap:
      - name: cnpg-default-monitoring
        key: queries
      - name: ov-postgres-custom-queries
        key: queries.yaml

  postgresql:
    shared_preload_libraries:
      - pg_stat_statements
    parameters:
      max_connections: "25"
      max_parallel_workers: "2"
      shared_buffers: "128MB"
      effective_cache_size: "768MB"
      work_mem: "8MB"
      maintenance_work_mem: "64MB"
      max_wal_size: "1GB"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      log_min_duration_statement: "250ms"
      log_lock_waits: "on"

  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
