apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-ov-postgres
spec:
  name: openveto
  owner: veto
  cluster:
    name: ov-postgres
  extensions:
  - name: vector
    ensure: present
