apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: ov
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:lajq7Q==,iv:jkr5/0hHcRF0n4NWnGzF7Xr8wmHXhuy8BTXugiuOzco=,tag:Uf2PDm2awUY/l18PmemG1w==,type:str]
    password: ENC[AES256_GCM,data:YZ+cyza147iDix61KQ==,iv:BA8lE8uln3RlE0PuAmPMgCG1Rf4NZcsQCTZ5oSym3Pc=,tag:dlV/b2UdMmEA94SvQVTgOg==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDJyZmxEMUdh
            TXhWSExRbU53M2t5VytDZi9MUlJYNVA2VDhkSm5sODFOSmZpT3JTVG1RQSswUi9E
            MGhaazg4UktOZ1pZaldIbUd6Y0U3cEo1Zm9vbmVHUjE3TDlPL1FJVW11Y2VGZjYz
            cXJJdnRhU3BVQjR3YStVUGtLaWEwZHBVTGdWV0p6TkhsNy9rWkJuL3QzYXFuUDQ1
            aUlIRmd5MnRHaGRQOG8rTVNOV0owbmt0TllTcFFwaTc3UWNuTU8rcnh2SkRHZTNi
            RWdVcWZlakh2TWY2U2QwM1dob3dFc1JlRFlDcFBvd0pIb1lWZXU4enNxeVRabm4v
            QzkvU2VHU2xMNGx0TzhlekNZejJXK0pJeWNkR3FNSFBybjhzbk5PTFBTUjUwL1o1
            Y1dUR25mb1pWZVUwMDYwejd1QU1zNGpoVk1CYWtvayt2UHFPWkl4ZEVzZlRGWWho
            STR2c2JqVzNUWUgzNUVMdTFzR0Jvc3R4WTZObm11Tk92YzZtN3lFSHBtSkpuZ3JN
            eTZ0T1RQVzZCaFdsM2xsdnZPV08vdTc0UEZvRnJMMllrN1QyZURiRFozajIrSkxq
            RzhJMGhZNGJKU3hTTXlSNVpyT1BSZkdWQlRkZm9mR3JFUXZhZlVVckNBcmpDWkdP
            TStTOWRpV1VsV2pzTmtzZ3VBeTN6SmROeXFodUltVUZ3UVlTcndQYVNtUWVvN3JL
            dEJzWkxCVDR2Y053SDdWZWNWRkZsaG9PVTBHdGtCcEVvRmpBM1plTXYvaTV0VDFQ
            STRFRkdUdVRHY3NEczU5Q1hBMWk3OWxKMmVuc3NFeDJ2dm1UTm1INEI1dDNGZ2Y1
            d0tmQitCQ0ZNNlBGb1F3VldqK3hLSjNaNEtpZEd2ejl0N0lPbHY2dUFDd2FwV1dx
            SHlPdGJUODJtQmtVVGxwK0dqU01kKzNNM3lUT01vQWFuRzVwbk4vUTBBMW1LMjZl
            NmFDWWN4VFpuVWxNUGM1Ynk2TmVRS3hhVk5uT3BuM1RvejdFMDRVODloZXQ5RWVN
            dmF2Q3B6bFVBcHFqWnQzbEpiaVNtS0RFS0tYbmRVN0JDYW5Jeld1c1djRzJxSG1m
            ZEZENTByYzZOeUgzVkNDYmlUaWYzbDFUSUhtcE02YlNCbWZQOHVVZlExRGtpK0Fa
            NGIrQndWWm5KUGZjRHNUNmVOYkZZeHpCRlp6NzEzL0NYdWdTU2puUUkvb1k3eE9H
            MGZwalZpSStxQThzbm5SV21sRFp1WGN5Mmw2a0FPZWQ1UkFKR011M3B3dVBuTm9W
            a2h1Tk5XMlo0ZGNqV0o1RFRCTUcxTERRU3JubFQyRStEYW5rRkpqWmJCMmlncDRN
            RHNaUndCT0h2SzdUblFFMVBEYmN5TW44VVNJUTNuaDcrOU1VdFc4Yld1dzZUTHJE
            WU5xbTgzdW0rcTY1VUtYQS9Ed1d6N3lRMGNuT3I0N3N2UWMzc0lQaCs3VHdjWGhS
            Uk94RHh0Q1BsYXJ1dm4wQitXTmR6SS85WEh1NERUa3dyLzIybzRJY2w0RmIrbXFt
            MEJmdkJIOXBySmZjK05VT3VEZTAyeHN4c2VESlZoSkVYcmZaN0JwMk95Zmd3QkhD
            S3N1am1vY1phVWIwUnlzekxQcmhZMDRDcXFiWEkzQ0VwQk5LM1RaT0hDc2dpL25x
            czJRemVNaUE4cjMwSFdrb0V6ZDE2Y1YzazE5S0FYS1djcjdIQXY4RGx5RC8zZS9J
            ZjJTelRXalo0bUdVdmF0VDRxbDVpQXhYODhsYktybDhVQ0djWVNzRlloL3lZdkVW
            U0FjMWZma0ZmUTV5bWtJamlIRm9kdElPNDljS0Z6THZDVTVvZ21MNmJUeXNGV3ls
            T04rOEtjNjM1WWpPV3MwN1FOU2g3YlgrTzA4WWc3c2lLOFZGSzhMNDQ5Slh2SXpy
            c2grVm9xV1pVK2Z2M09BcXpKZkhaWnVwWEhobVhpWGlZU3BycnlMOWdYTjJHUQo0
            dThmYmUwdmI3SDhiY2V3c2UyWlN3ZW9oL0JjQW9lNWVId0hGWlNadis4Ci0tLSBn
            NVdSYTMrQVNjZ3ExRVFEcGNjUTBWMGplbVU0ZnB5SWdsSG11YTIvSEpBCoT1Zvrs
            tPL+pc3Mch2aY0P23DcGQJn7w2LBRWmVGsiiJ3qOVarlFL9Oxi6CnhT2gbEUV0fG
            KfMmAdEXQ+ya0Iw=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-11T07:30:10Z"
    mac: ENC[AES256_GCM,data:+SACNWzq9TMxAU0Y070onpIdX7YdXDfd2eRPBItRyZ1PzOiZjkHUAyedswGomySMbXxWY8Up0sycdIPgIYd831hs0DNvWUUhve5sT69RznrDA68WEFy9rqmq+QLJheM3614RMrAgi51tHyA5m449Niiw685P+sw2dxpPsoI3ThU=,iv:vgqZpjzsgwaoXDaHUsyfK/rwj8yMZ3aA3ZeH9NjVeIA=,tag:zGajSR+PazXPPKow6XTTyQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
