apiVersion: v1
kind: Secret
metadata:
    name: backup-rustfs-credentials
    namespace: ac
type: Opaque
stringData:
    access-key: ENC[AES256_GCM,data:5m9NxvfMpq2nCosSbSZIAzz9Tvk=,iv:bD0Dr+7tzb1/I4ZFUMrC0imeo+I+ulDg/iZj3ypjcoM=,tag:9TRkxHrrqWOpSV79Kp2bYA==,type:str]
    secret-key: ENC[AES256_GCM,data:cnJlTr87mdkWfichuL69r5w3ykF5M4liImxX+qIowhCavu3W5qnhbnRBI+Y=,iv:Y4K/rLqEad5FcRe8XIFW7oMeEbCg0kEJ8/7Rrj9b7Ig=,tag:QoA7hhqjlwNRYOTzlEeLAw==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDNXVjJTUzJi
            alN1bVhvNlpuaVpJRUgwSGZNYXd0NVRVaThXYU5rampJUmlkUkx2MnE3bTgxY3Zn
            TVRTNFdIamQ0aGxmU3A3TWJOWDRTTitiK2gvYUlZNFFJNk9LdUtFWk4vaWV4YW9y
            WUVZYTN3eEk1eUpjQUNEVUUvM1dzZUhzMXZVdUJGOVJWSmVXL1Q4YjFDYzBXN1Nz
            WGo0RkxLQWJFN1c2NG56bGxPWmczNmhvRUFCK3N6NlBpejNtMFVsYU1UMjNOYi9U
            enlQZUpCaWFhMUNnczQ4MVN3QzlrbG5lTmZjRCtTcmFHZzF6cFIxQ3JURjdYKzJY
            dEJMVGdXMWNzYjFSN2VCZXRkejluSUFoalFkN3EvaWVjTWxtb2hZeE54ajZVMnp6
            VEhyd3hlUU5qYmt6SjhJTkxycnZEb2IxR0gzZWNucjlBSjZza0tWOWZDdDlXcFNr
            ZWZ6RlAwemt1OXFqdWpYYVM3dWlWUDZXQzV5YjlhRU1Nek1qU1pCb1J3REtKLzNh
            WmhMVC9YUFBlN2ZFa2FFWjBWZHJPUXo0elUwMjYwVmpBTStXNTZRRnZLLy9UL1Qy
            WmwrUk1wMjlmcXlhVFpNQlhQRVpQbjBxZVI1VGU3eFhxZWVNTnFtbzZJMUNrMnFt
            RGlvWTFYZEtDRW1WL09HSkNzc08xdmwzYVpmV0ZvN1dTZnhoT2FpWnQ4UVIvRnhF
            UFhSQ1U2TEpDcmsvbXMrNzRSWm9GbzljUFFPZmNCUHgxVDdxOGxJWDRZU3grUmli
            SEpnajlnd2Z1V1dURzEwVXo0Wk54QWdZVS9kMy8rZjNnUWJtWXZBZ29ncUdnMnFt
            SzFpZVgyZEV1ZHhkQlg5NFFPN25SVGpzdjdKRm9adnlFMVZseTJvd2U1cDNyUDhS
            enIrMXBseTdDQi9SdlFCcjlhTHJScjVBbU9iK21vdG1DRzdYYm5Vb0lQdE0wQnM4
            b1F6ejZIS3ZZcmFyTFB4aDBxU1BMQ0YyRW1EY3p6WTBYbEJYRXBVSnlkSTBUcTV4
            SmRKOTRQMXhGZXBZRlQvT20zc0x0dmNNVHhxV21zTS9yV09rTU1hTzYrc201UURV
            azREWTQ4THE5Sjk4R1JCSGJJTlI4Zzlnd3hIZVNXVmVSN2tjb0dsZ0dyRWFxOWF5
            Qy9Nc3UxOWhLbU8yNVFZRkFyQ2JDa1pkOXVLRnU1N09MeWhmakttODI4bVpEY1RI
            L2JQZVlRQjFtY3NPZjU3RnlST3Y2aEMzblF3dW1DcU14THZBeko5T0h6bXpQUEo5
            UlNVNkxHSzdrUDVwaEdkSU5uY3FmdjF6OGV3aFhtYlFOS2xQYitjOUF1MXZQbjBy
            UUNWWUZPLzFPTzczWExBV1FMeHhGNE9aMmRzeDdWZkNYYnJtWXYrRjVncjBOdUZJ
            c05yVkZOSFhCUTU3TkVMVVlCZGNmekYwOHZ2aXNoVDRKREhyU1BEU2FrUWhvcjdv
            NzBXL0hyeWduSCszL0tjR05xK3RtVmszZDhnWEdJSEN1OVdMRGZvb1NJczI4MnJ4
            dVhNQk94OWc1cU8rWThSVHNVTEdLOElZWU5nWU1CWWJQQ3o3SE1GNDU3ZWovK09i
            SmlTOHFDSXQ0SzJMcHpLRkJXK2VkY1B3dHErR3pkTUE3WHJHaXhCUHNvcFFBZ2RH
            OUdWK2N0S3dFNDZkRDh0TXRxd3BQL09pVFVYWWZzdkRxUFdSOFBQeEhtTjF5aDlq
            L2ZSVEl3Nk5uS0hXUkNvYWpPcVVvNTlmU0NYQldzTlZFWTBqUG4vck9GTW4vYkUw
            RUFzZFlDNkRKZ2JmVmd6R2FnVEttS1AwYWE1ck9FdC9LQjR5ZS9oL01XQW9BQ01a
            VlVYK20xbnQ3Y3dKeGlsMlB1U2F5am5Ld3E4VDNWbm9wV3VRb1c4K1VkRmt1SmxY
            L2RFZ2tDZEQ0ZnoyK29QV01wMUxnVnJSSjB1SWVVQ2hVcHpZNnU1Q2l5T3BSUQpr
            emNnR25RR3AvR21aRVlqYXNsa0hsOG95L00wMmhUNjh1anlBcVEvUkMwCi0tLSBW
            L0t4WTlMMXljYjRzNENlY21iS3c5bUhoNElGUHZ0aG9DSjNIenNoRnZ3Csbupqd4
            BZBXyFk1bg6ilOt7D6Y/aoJZGur4N6UMvk+8/K0cnLG3doK21nEW4ijfpnNWhiv+
            qpk2CfqJUVJ2HhY=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-09T06:38:07Z"
    mac: ENC[AES256_GCM,data:xUr8YSs+AzuGVM5EkXQHwOkNjJQsGuGH81X8mUqG0L1zijglALFntf55jD5/Bo6/aEeVWwkjbs7olepx0Fnxh8oQ6eSt9ctnm08MV5ZlUv6BDdep1wmX36Wo/WUkJEAZlRcNuiEd+rUm9pigYpUUC6ddHAarcaTi0YwNMCJSse8=,iv:iZG/De1R5Nb7QbWyzvj7YR8MTQeBpskXGg4o32+FsDA=,tag:StkyznQs6BJvOOGYVqBYyA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
