apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-ac-postgres
spec:
  name: ac
  owner: ac
  cluster:
    name: ac-postgres
  extensions:
  - name: vector
    ensure: present
    # renovate: suite=trixie-pgdg depName=postgresql-18-pgvector extractVersion=^(?<version>\d+\.\d+\.\d+)
    version: '0.8.2'
