apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-ac-postgres
spec:
  name: ac
  owner: ac
  cluster:
    name: ac-postgres
  extensions:
  - name: vector
    ensure: present
