---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: ac-postgres
spec:
  retentionPolicy: "7d"
  configuration:
    destinationPath: "s3://backups/ac-postgres"
    endpointURL: "http://backup-rustfs.backup.svc.cluster.local:9000"
    s3Credentials:
      accessKeyId:
        name: backup-rustfs-credentials
        key: access-key
      secretAccessKey:
        name: backup-rustfs-credentials
        key: secret-key
    wal:
      compression: gzip
    data:
      compression: gzip
