apiVersion: v1
kind: Secret
metadata:
    name: postgres-credentials
    namespace: ac
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:hH0=,iv:QXh/NAF+pJiiOOAqNrZ3nFD4pANYIl2KKKvdjiP2Xas=,tag:t9+lI2HMtPPXtiXjDgK3Qw==,type:str]
    password: ENC[AES256_GCM,data:UEn9r3cJw08FTqMjYjZZRSTNzhCh68M2,iv:jThzAp4DOZUit9EnqSwee/6hrpXVP7fz1j6jo3rGk0g=,tag:q4pN58yWp1jyu4JrLJnq8A==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGFjVEVUcmJz
            VXlGVHdTd3JDZWU0dTdDZGw2d3lKNU14T2h1YnowVytsNU9aVnc5SVNnVXI3VFpa
            citkcjErN3QrczRPZW1qdHF6QktlZnBUc0hEbGJsUWQ0eEVxK1NWYzN3cFB6Vmds
            clFSWTFLRGIwdHdtNVdrbDZNbmZyVW1ZdlpWdFhwd24wV3BWY05rSTk5Um9iTUdo
            NE10NzZkODhBSkMwaGdLdVFVVlJ3YUhCeTgwSWJQOXVjYmNhZitBeXNLT2FZMWRH
            aWVHcHVwNUpJbk9JeWlhMzBaUU5IYVF5Mm50dEcxeFVLdWFieWdiTUpnaTFWa2lR
            bFYwZHFvMWRoR2hlS25LTW0zQTgzcFZ0eU43YWovbkdYOXh0REVtS3pXcWV3U2N6
            Smt5YXVZWWhJSk5mZHZ2TFFiRVV0RGNsYXJ1WktYK0dlNTlxR0xXMk5yWkFBL2N6
            WExRRnA5WnhKNFNWQVFkNml2Z3FmVWthbGU4M2NucmRValFIbG1pWUhCT0p4U2pP
            MDMwNU9WckFMUG9weFB2eTRpYnZuQUFDQ0l1QmdiMko4Z3F2aG5WWlVqdEJmMWRj
            NVk2clpUWkhGaEpUR0RoTVMwRlF0T3dsK2g4dUpTaGF6OG5ZV3RVWWdWZmx5dHZz
            aDJEc0FvOGYvcFBRelJkZnFIbHBsQ3g4UTJDRTFtTHNvMldFRVNCVSt4QWRRTkht
            SXNVdVp4eHI0bCtYMlo4QWkwTDJBdk1HQTVLWlpIUGtJcWN1Y1F1M2pRNUJrMHRH
            ZU1OdkRYeDVDQWVRVDcyTDZsM0wxMW5paE8vZHBYQlpzOHBQSk5xemhmeEVIa09m
            ZUk1eDlxdlhTZHB6QkhUMVRCQUlPd0RNVTRsSllSLzljK2kvUUYwcVIzSFZEancv
            bU01QTlISDAzTmIxZkk1cmdKRWkrWG1nb0RQUXozWXkvNFkrNzJtWWFreUdmSnZF
            TU85L0tydUIzWGNya1ppMm5SKzJTSnJSeUxOTTBsUnhJTExZMUcxZ2prRVAycUVD
            akMvcjhXNlJteTcrNDFGaW0rSVpJOExVc1BQb3UxTWxZcnR1MXo5YWpCemV0S1Az
            U0NPcm5SSk4zRkpRT1BaclBFUmk4ZFRBZEdhbFFkaXpWelZXblBJVE5HbTFoUWhq
            bnRyNFJCY0luSmt3U0szdEM2c29jRXFpYko5cDlucDJ0UEVSR2lyQ243VFdoWE9j
            OWgwZnFscWMyL2p3NWZXczhmSGtxMG0vUFdSdXpPQUNxWGhodkxGOG43U0FYTmZr
            OXZRakFhK0ovVDMxSlNhQ0pVSnBXRTEyTEtZR1FwN2gyQVVMVzczZTJUVStlMXVi
            M2FZcllHZmRFYU9HMmRzSzA1K2diZVdrRUhuQTJQR0ZBWFJ1bHZ6WnY4dUNib1Ew
            ZGFFT1NUd1dlQVIzMWFCd3BuYnpGRDNmelIyVU1lc3lrTTdadkxCV3FsS09FMW95
            MVQ0azZTOXZaVG1YQXNMMkFTZ0xRSkYrcXp6bU9Dcy9qRFF0R1dacWRsTmg2MDYy
            a0RzbWlrbkpsSTB6bVdwSlRnTjF4cnhqczkrTDliZWNyTlZYTkljWTBYR0ZhSTlq
            Tkk5NjVVZTlEZkxEaWlZSVVWU00rNXp5aHNhd3FpMU9QYUR1eHJxcmd5T2E3MDZR
            cURkUGZMUlNaM2lCdUFQY29kWU4yYTVwdmFzMktFV3Y3TTh5eldPMGFKRUZsYWxX
            N0s0Z1hKU3oxOHBNdjQ4N3llWWxTNXdadm90N0tGRG5KSk5YUnprYTJ2MUhxbTg2
            MTJtSjVWVmlQUmFjQ3czRUt2STczL09QWnplWjRMTThwV0pYelRSTjRMUHh6aTJX
            M0ZiK05DejRTNmpuN1NwQTJuN09rdkdnUGRhZ0x4bUxUZWhlNTNqVG1qZDBnbjZH
            V1B5UHpvYytsek5KckJrOFRmUDFaM1hZcDhETlc3cU1TZXpDT3NiWmZUU1FRZwpQ
            RFRjQUtYUXhZYmF6NHBUYTJuNjZKbzNTS1NDT0F4bndza0NHZjR5TXBJCi0tLSBs
            dkJFNnVIZ3B2ZDNsS2VKQ2ZTOWF3UitFZXhBdlJpK0o4SDZvMkpibGZzCuF90SZi
            YOiXDPzkgW0O3n9dqDlq8e55pRvrQ+XmrN/7dvsPBIrZDaxP8cLfw0aVejRppfAP
            zTQBQVKl0DqpI2M=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T03:44:02Z"
    mac: ENC[AES256_GCM,data:jbQ7FVGSdlbPsVCA0AV1PmZuOTFBSfd932vbdr7HcjewHFxbHtZu1aqodktApZqiVLhWXRU6X+CHFzeVoKM+a0zVhlxQ9KH5uqLv2YZrlOWr4AkgljR4SohAnC32r+KI3HSxuvVP6T2lKgGqpTnFQATL0SjigwTWWaC8SoxbVxc=,iv:AcU1xQhsPdmp+zRUowtRroI3lqVKRlpMNfjDovoOxLI=,tag:USSAqg6zWOTCKma8jiu0/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
