apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: ac
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:9Xm3WTkVLAiib1s7jl+hSe9ldORUtZ5i53H622rvNFwaA19h5o7v6r26PSQ=,iv:ForbF+wCh+AXgoiFaUTUwd/s6httDsgMXXax2aUizWM=,tag:44EWKC6W4/zVrlcbmk0nwQ==,type:str]
sops:
    age:
        - recipient: age1pq1m8fee0mfkh6fzw635qffd33y99fmjrr80k2r4zv7wkfguegp0lgv836ryfypgmdnjvxq243lvh7ftfx2wr6azz7t6mqhqsxdxse3hysqk3a63vlllpjha6j4rn729gnzhfjn2qy89dp0ce5k0wq5ed7fpn5msnkhegp8qeyelxxgxtlnea6cg7sd2jche7zcl2jsrnjfqgrwhj4xveyg7w4ffv4e3rrref5mg47n6gqxqfyxacft89dqp668vmvx6jnuxvne4na5haxs3z3zxlsqvxqqaksvjk3xlhegr4n6smd63t8l5e7x8t2pf68nq2l2z89cqk2c3h9277gj6mlvr94h9tfk5fzkktyqtjy66fuxvhj2xgqfydwsne5gn02e0rp80rd2nw4akwz3p7cuxkfhq2nuhlh9j6wqxandlcehrznnmeyun4wew83lezdu9fm484u50ql8vtpfdv8ckgmp3tyfk4gkvl9qc0dnglqj3jqvgjgjegqq6hlcdhj748mtayrcrjmgjevcfkzf2jnzzn6m4jkn26ev7ggcnqrj9nwvvngntp2ef6pj3w5ta0ufz5yetzhaskjztc2glxjtelr29nym5rdyg4yl8z33tsngxvgy5wm9kaa43xm2ax7xsu6mnqzvemxlw0n7nz4afuus87p9kvavxh8j0vvtsgjd2ejq5g38eny6j7u5p36unyw78v4m37azgln2ys3ltvnluzyg77cmlyzh7qypdqmx08zd7g43qz4lza69qa2qgwmajs85wwcc0uqc50c2tr7kxmsuryemqqew48qqvccx67u6csj0c8wrwj0a8e6q33svsq5jd0tf53t0k6rhfeah2kkpj68rwk0x4dwc8rrxl4p956u8t285cypwtqa7eqad77el926hqn05jdnjsxzdm3d2t9f3rg6ju73gp4xxgaf642atgxefhztzg9an9cj4pstk39jlkjplfz3m5rwt87skxjyrg48a8a9k497zfpjtpufejzfqjc9umpd6mrwrgjaxqqa243n3hq3vu7tyk663p5sepehdc99m7e3ulumrjt7psw7edgkdg6htjdntq4upzp9jf90s2pu74w7375m67cgenzj5ms3r4hlvjxe5tyzem69wmx26quuesdyzke9vnwgl2dpnwxv2t0m95tvswu4gnqnvdfejsjy68mhxr4c7ez5rhtr4cf5f8s25acvp0u0e328j8g8gs79607qnev08flf7c4as7ctepqd0z23gxjphhddtr90mpdn85ypvrxyklw3rqp5udp5zkc6n4vt3q72qcayhzvfj4299zajnsskz7t3u272evzn3s8ldcy54q4tmeg325z5h3glyz6g4fjkvduwvcldq2wccydej5umv8g8ks8r9st9xyeup36ys3jh9pw067k590tusp4qn8vq45kcak8xrztr9h9n8ms4msatzctcgkppgsj2xk4vkjrmgvgn2dr7syaugkfc44u5p6w4557q033nnuvtp03r9sfzxeuf4y8azwdgsu5zkkuj2evc5eu62cvtwsmte02pc47a7nhxqyuanctqk2rm5z5yy2xm0gx2zgl3uwmkznscuw0z8d9d6k8g4hh9xrgl293y0qx5ng3uz5uvpxv95hmzl9xf3uz4mn6c5w6a5c8538u6mz060rdh3pz3z565ze9n6e7l2tnyt8yzvyzdh8evxez2xfwv6skmsdjsl8gc0cynth82etff89vmc2f0ez5905rkgtzzenrx4zvnchspveffk0d2tj6fpg86h5qp0seh04p6uer7z0ljuj08tv0yr6fdmaezgwvtewreytgmmn7anm0sy4vm8t665rxuvl9q24pqmrxypuaas97cj0za9c8vtdknkcmu9aj8z8hr0v4m39rc8y9e946ncfrzngq37y5ux
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IDQ3TlBDbU1Q
            K1I4a2g3WEFCd0MycFRZZ3Fqcjk1M1M5aG9xODk2ci9UeVBMZ3BwQWpjSE9lSWtR
            VHlPSWpITTUyTXN0TVNTL1BCRmJsQUJPR1FLNnZlb3NYRUxjajB3S2J3aGIxWExu
            dXREN3UwRWtiV3ZHUkRMa1hpdW5NSGIrSG5aM1ExZmFIZ3pGMlA2S3JScXhNVnZv
            R1VDV1U5Z3dna0Y0amZvbFRmUlRUR0FBQ3JSNWlKQTdZTXcxWUt2b0RJaktkOTlZ
            NjE5MXVSV1ErTmE2OHZvNzdEb3lzTFo1RWFWdkt5RnJ6ZTZUbnpiL3JoTXZIZGVQ
            ZEdtTDJacS9lSE9sVkhsS0VudFVLMjVTeXo1MGhBQmJPazZndzF3dStiVzJDQ0dG
            RjF3VXJDR29ZellEYzlSN1pXSXF2Ly9paVJoZzYyQzRNMXZNR1lPeWdwMmhBdlRm
            eEVWSDF0aFZEaHJkaS9OWm1QNU41NkRpVnJkMWtBaDVBUm02RUd6UjBMeklrSWJT
            NmNzaU5vQlVYMm95WnZyaDRqWmxXNXEvN3ovbnJDM1Rha0FQWG5EdnJMY1pKRjRI
            RWkyTnlZZE1vZUNmUkdEU1pSd21OdSsvQW50UHBUYWRTdzFWSUlIMnFsK3QyUmRI
            R292Zko2TG4wcHFWOHBrTEJvclpvY0VnaTRBeDFub1ZZaVV6Zyt6SGZRMEtFTml4
            THNyU2ZjK0Evc0s0UHZiNnJDSnNQUW9KZWpKc0FUUTdTWUlrSlRuK3JZc3JLRHB1
            ckxYM3h6cmpRWWM3Z201Q3I4NWRvTDUvd3VtWC9rOVdlUXhCRnZ1ZDgySnRZUXU2
            MlZ3emJUYVZmV2JrUUtTNEx4WEFta1BheE5LNkpzRVAyR0V1QktsZFYzN0d4aDBk
            QUFuQTY5UEZ2a0Q2NGVSekxNUjFLMXJiVEIwWm05UE8wZDBtM0F0THQ1eFJFUFlZ
            QUJiaGlBWEpkc01Lb2tTQnMwTGtFcFlBNDlLSHk2YUtyeWpJeHpxTC9neVZXT24w
            ejNPd3MvV1pPbWpibXc5dm1xcGNxVWNlOEZxQ2JucFdrTU1EZHdkSS91Vk0wOXpE
            bkpIbWlXZjFMSFJ3TjFkSUZWbkFmTXlUaENxVUNNS1k1azdtREFYd0RsSW5raGVz
            RG00bUVLVjB2ZkJSaWdOZkI5VkZLV3dUU29EYVByUTh4VUQ5Y3JvUFlSZEhKUE91
            QzhPNi85Y01BYTgrMEpzNzFLZWRobUtydjlRTEo0U0dzZUVzbFdKZTVmWnlhTW0z
            Y21QRW9oemJxN0pmWUNvRGo4TlhsUVk4SVVTTi9QT3h4aXFXRlQvalB1STZHNUZs
            YVYwbWUxME1uekdsWU8xV2hxOWFDNHNQMU45OGJ3amVuM3RKTGN6UDdKc2FFZFlE
            WENmZ0ZSS2RVVHo2aWxLR3hydzN3K2dLUktSL3FxRWVXY2U0dFJBVElzVUR3aytz
            Vy9aT1RlVVpFMlpOOXA5TUx1RXpEM2FtZVRUM2sxcnlEN3B6MU56VjQ2a3YrMmo5
            K250a1ZRbTBmMnFwQUx5NmpmZ3d6ampKSjByNG82VFZZa0w3TXZBYzNIVjZ0SFNH
            TEE2SThuL2UybjZJR0dPLzFHSEVLZSszOUpBSUhEU3FBQjRGZGQ1U1hyd1VWTHox
            U1NzMzN4ZHBUcnBuaFNTZWRXSml1R2RPd3lUdTV6V2k1TXJaaW51ODFZbytLeWVC
            V2d0QU0zaHJZaWpBMVlQdG5ZbldWL3p3UkNoRVNkQmxacDlIa2RMY0JvVFlyVEFt
            VjdEYkhTMEFERzhiNkhEV2lBOUdJU1YvVTZ3UjAzazBiK041UDMxMXNlek1uRTRu
            ZS9WV2FHanI1QWNUbjRWYXAycWFGWExqcVhYQXYxNjdjWTB1cWpPMkwvVHIzeTZO
            Qk96Vm90c2JjN205dlkraStpdXNCeUZyZGhKNDcycFpBVXphVThYRkEzZlNBdwo3
            YlhVNVVHc2l6TFdmaG1ic2Q4TmJUTFZrdGFOS3JwdmdhTlFta1pQTDhnCi0tLSBk
            c2VzNlgyNHVnNnU5b2JCU3RyREN1cE9YdnUvVEJoelJSL1JweEJLK3g0CkxkQw0m
            f3BXn0gu8czG/d36xj/zCUCg0npmbK25t6e2q4GcfTPdYFej/wUtaRt4yjyGCMiD
            H3AfXDZUiTJCfzU=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-21T05:49:43Z"
    mac: ENC[AES256_GCM,data:Lr5RYIWI3/kIao41ZTRvTrZYKov/hzLmChkX35NNvraGG0UPCfRYpFNnBWnqlth6AF9DJV2ljoKM6LS4Pm2DSpRqDk4f2liagqjy9yvV/TLm4/mcdSoj2IveDhgBt/9NruyFp5llQsMU2+C8Od3RwCMSBqrAUo0wV874CYNdXyQ=,iv:97moaxCq7MpRyAbdx2ZqN0N8AJ9XaygdPDA2SubaYjc=,tag:GodPR+DXCGfdGuhXCkn6+A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
