apiVersion: v1
kind: Secret
metadata:
    name: client-info-secret
    namespace: synologi-csi
type: Opaque
stringData:
    client-info.yml: ENC[AES256_GCM,data:W7PBQ252oaSQLib+JfdqCuMbz/xRoUdlCvZo41uHLDvhUp+euitSN2MbMLe/8gZ6UwzY+y3q4aG06XXVCaYF1f7jQDQMlpKLrqcu7umuRY41uMRmkJyFxi/1N5FxSqX/C7JkcU2W9KZGOC6fWNyPmRogIXP+MDt0luZVwjecRT0piKhQO2cuGtfxRqdmxXteQJK7AYBaE5sXQsbHbf9CcrlnnGPS1vd8EW97J+kA8rPWCGckAcii7eXPFS68aoU9vXnwl5UqBHWE398/0q6ZKMaF,iv:47GAU9GRLibVOyA3vEz2tbLQ6WGmdQG3JusWFbTBrg0=,tag:N7zQLdAt38e9l7zD6V79tw==,type:str]
sops:
    age:
        - recipient: age1pq1r9dyqput53j0dw3agxvs4xg2aqs9fp2x3n4s2h23pd7xad9jmvtrc3vgtz0wvkugq63z4s67puft98n3d3lafx9yca2s9eqq82spal5swmj9kcsyfs7fy7jt3wsmaw6z89zxjq52dy5knvm5tl9v73vypteln38aw24345az4mefwqeeelzhjasa5lrrfk4tqe33k8q84an79zpnzuysxdptt955xj4mq4gvpx5p3pj3n4ugv0vrkx3updx5yf3mpfscljvmxn3q35ztysnv0vc366nkhpgg8rstulaz2rs5yj28fz6rqwu56p3xw3ec9n4t03zc0jznxcdn6eavd80xj7ljxmhdfv4s6z699a7xswsjpe52nxcllvareg5n905f2lh80csk9gdgf3ua46dalttmrm9cgpldnzge0vhdldt7rqujt8uyja9ner7hqkptevyh4kdz5vc4dcv0h00s9q344cfxf8j42sfndhu320uq7stcxq3q2yd6xn45f3pvef2q0fh6fuf7sxtz30f3qkgqtrlpqd3dgyuwkacuw3dtxl9zgh98eq29875wme3hh3qn2cy7wzhu3w968crqh43maxyk4lrlvdu4ld2ltvmffyetsyt5x32l5fnc7u85u4p7aey5c8y4gca8qlklfnqyutz38g9g6g2svlq7hqpj764zvdzxrr5yrl78rd6nf2m26xuxf7vk0tt6wmfmknwjk469z9zq0ws3dws4th4fzkx3qnpvw2e04fk0v5kz27x3n8q6wtfcveqsthqjjcf970n8wrlyfyptyjk9a5gtjta5zjnfc69sc6uakd0vug7z9npz2eujzg3vw4cc33sc2rxqc9je46qqgwnrhfj8zurc0xq90t24prsjfw3akz5c2kyu8ufvn0p596wrp0875prgyzq2d9mgy8cfsvxfsy40rj3ggaxwfcxtmpgzawuuek0426qmhfn8sjsfhrqnsfahtshjydyny5858kzdgnas8h8r48skx8nmvk6kzvt893q59slqkdd6wxnw2xw3zcfkpqp4txfk2gg6n8p4cph7jx45gu9mz9f3eykaxn9p0t8tv36c3y5expp58fk3eyhsp3tl9u5jdczu4q4s2awmkdjpuk5tadt4fsv4924tvrfeyqu8pf0k7pymze9jc7mnk6wgj26m00yxq26xshuqa6py03ays9yuyz62xxmqchytt69zvg7vcjq4ugzxahp50gfye7zvghwmym4yejqeyjferanvy9le3ksszaewcat2kcg5gp4p2ezf36cmr2vh6ysztrrquauz7fq5n2d233w92s3kqgjl78m58m9r0rjr9wzjc3235szs4p9jv5r9hhexjr4ccka3a9w07m5rd6preex489hu7f3fwfyz489kn35ergzqtndgadmqd2atxds4s3vsrluz3skcvqvmqqpwhtc80d2rs8z0gq7eaddggxqyu6j9lht4vg3pc9l62aeps9nq5h5p6tzzc3pp5wwwyj0qfapp27r6xt0mp6j72tcnr3ta0mzgdc36hq8jwxya9farf2s5hyn8usmtxy9vgu4wjvyl8w9nndawwl5y8tsudteuwn097d6sl95k77dnspl6ek2k9gptc2usju29fsmk4cxz4thlwp6v9yv8qxkyscdklh3m9tz73rk657zt4vpzlevc537kt3x9q90rewyjrdjtydach8x25gq0rsam7w57npzs6aehmjp6w6hj4n9e6ktr63wt4gpzgs0gvycyzckrp3ue7yrvv7azgkk8tlhsh3avf3cf69tn0ntc26gy5y3xj0jalggvgm83kpv8kgeg7zg0g4r67g5ndnxm3xgluhqu5mhzpntlqpccdesnh2cpawuja52ledlacs9p0vv3za0jauzmy4h25yz6mlpm5t57w5r85mfr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFhCWUpaUll0
            V2w5V2JhK1NieUwzeEtrUldIY0QzZ0xTN1hvUjFJZUNKeEttYVd3YU9CYm9DdGds
            dE5UVC9XRm5jNG5pczdTdnhUYlE1cnZCbWc5SHlDeUFZbkRxRHJ2YS94OXdHZXpt
            cnVTMWdEL0JtMUdUQTlzaXBYM21RMi80QzA0RXlrZnpWa1FCS0N0TC9ORkFPdjRz
            dWlhWTAyYXRJcDE0TkpoVW1UbHBFamd4NlVTMnE2THZnQU5JRVJuRzZXaVFqVk82
            T0NxWWFwSVZadTBSaFZQT1NlTGErcHZPN0VuQzM2eE5zZFdwNGQrZkcwTVRZcDl3
            YmNsQ3NmOFJIUzZOYjVLNmp4eGxEUXFHQWNRcllaUjQ2SnBMcnEwRmhIVW5oWUhI
            dFJmcngxSlFoM0hQcUhyRkpzZ2VqSXFMTS9PK215VHh4K2NGZy9YSjR0bkljNHFw
            VHJxcFFCbm8za25mSE5WWU5wZXI1bnd1SlM3ODlCTURwU3ZMSGhEN1A3TGw3dktE
            U2wwcUNDVmFiak05VUljMms3elNNcTNZM3NMTE81K2lMYTNVQmRXY1ZobEJHbVR6
            U05IUjE0c3ExQVFZM3R1azk3TG9EeUVXTzlCZXZ2Vk1YNEZNdEVFcnhlWmtaZW1G
            SGVyaW8wblR2bGZnblpiR2pWTkduYlFWUkE1OHFIMjdKUXhwN0RXSUVSa0svSGFm
            Y2MzN25VYnVoZWJVeStjY3NMM2FRbkNKbGJPV1BFR1NtYzZVNXVxL2lRSHN3T3U0
            NGtnU1ptMzJKakZTeENxcEZSQlVnZ1BCRFdYQ2hyRnNXT1RDWlpnQkYxTFdLRmFo
            Z3NzUEhoV2E4Y0krdSs4cEVIUlJZOE5FbTZsd3RjOVg0bFNWbXZ6Yi9pYWFCMndo
            cHEvdVhzU1dkcHJRdjJMSEkyejh1N1NqQno3b1pnWXkvQnBHMzVNUXhkZG5CV3lL
            ekcxSFM5dVViYTN0UmJEN1ZZQ05tdGE2K000aS9wQlUyaFJUTmhjbkFMTHBBTGdp
            UmpnQ1A0NmFDa3JndGRIUTF5QWJJYmZnSitld2Z4UDBnYlRnbExpNVN5d1RnTnVL
            a2F4UHAyS0pyMWJrNjZyZ2loNU5UQzZwaXNybHE4dFJ6RWZLSTlGR2VSTW4wYmVJ
            SERsU08vRVkzd1g5R3B3bUNSbVVHb3MydWp3OVJVM2NYY3NqMG9MMDlOV3FKaFJP
            MS9WZnhzU1hlam9ZY04rSHFHUVFYK0I1S3VUempETnRpcjhTSng1dEMvRDRGdEJj
            T2sxT2hGY0dIWE04T3lSeXVqYjZleStYOUEyQlBYY0dlUmh0VEhlR2pTOVR2WXk2
            Mk9aWlQyOWNDV2tDWVphV2d0WVc3THh4dzdlYjFlc3lZMUltanJpcEpxNzB1TWsx
            cStrTFMvVjl1dEl5OWo3ZTN6WDBzTFJxOFpuQ0xrdWV1Lzk0VXUrWHdPbXNzRzgx
            M2toUGdPL09ZRDM5amFLZFBkOTR3RVBNTEd1Nlp6K0ZjOWF1R3FlUWZZNVBYSTRm
            NVQxQzNQblh0a0xNYjhhOE9VU3JmbU1oUWYxbFFlcEx4UXdqcFJyZk0vcElrT0NV
            R1FoUXByOVJHY0pNRlozT1pROGZROXRiMjZMT2NhcUdNdkFtN2JOc0krQVJqZE5B
            aVd1R05SY2FhVkFITzhWOTMrNFZxUGo4bjB5YjNKTmVVaCsxdGdpRWNqZXk3UHBl
            VXdrVUhRTko4NVQ5SkJNTjJ0bkdWbmlPUDBBaFFjam9JUmtYbWVXWUV4czBGcVJQ
            NDZtWXpvTmhLVGc3WWVXYmhJUEwrM3RiNWhvWTRsVWZ1WWNGb1ZXKzR2bHNMcGJv
            NFFjWXk0Tkd2MVV0OTRXSnZaZVpWVUdpc0hwY0NZRFRsSGpyMmpVdXp5QzA2N1Qx
            OThEZnNabnBSN3RVcVlJVk1HUVh1Vm0wQXNDSXdWOUdSRzJCV1RxclVvQTVlUQp3
            ZXJnK3hVOU9FbzRTUzVQZ1NjdU5jN0RMTElEN2hXTFBUM2lYVXBESjJVCi0tLSB0
            MHlaNzhOMjBQM1NpZGZUcnFlQXp4ZkwwajJ2Tjg4Y1F1aDFHclZaT1hBCqDzDUka
            uWpGbF0JNe/P3ql3ujuegMqzHB5Egq15xSiYWOGchG2POhTdz3chJKD8JqZ/fNsr
            9JedDXormQA4FE4=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-01T01:24:15Z"
    mac: ENC[AES256_GCM,data:We4SLq57yw+AEHsKJCskGUuz2H2YvPCrzDt1JHgutLWcD7fp2kEhgY72xYo5rmkZcfgXBo0eKGwfPqQJRTcGkF0LsiDwgiuLsvq7w7TOpQmsqeeNALKro/55F1kXBDsoaTtPwAkI7hzCXBzQx36bcAEBQBgI/vCSHuc3idVusYo=,iv:KrqskyIBX5Tbd+8ki6tROfkrygp9l2epeYZorGJmfxs=,tag:w3qZGXNSHH/q9xSK49KYzg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
