# source: https://github.com/temporalio/helm-charts/blob/main/charts/temporal/values.yaml

server:
  replicaCount: 1

  config:
    persistence:
      defaultStore: default
      visibilityStore: visibility
      datastores:
        default:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: temporal-postgres-rw:5432
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-postgres-credentials
            secretKey: password
            createDatabase: false
            manageSchema: true
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h
        visibility:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: temporal-postgres-rw:5432
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-postgres-credentials
            secretKey: password
            createDatabase: false
            manageSchema: true
            maxConns: 20
            maxIdleConns: 20
            maxConnLifetime: 1h

  frontend:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi

  history:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 768Mi

  matching:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 512Mi

  worker:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi

web:
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  ingress:
    enabled: true
    className: traefik-internal
    annotations:
      cert-manager.io/cluster-issuer: lets-encrypt-packet-fail
      external-dns.alpha.kubernetes.io/hostname: temporal-nuc01.packet.fail
    hosts:
      - "temporal-nuc01.packet.fail/"
    tls:
      - secretName: temporal-nuc01-tls
        hosts:
          - temporal-nuc01.packet.fail
