---
apiVersion: dns.packet.fail/v1alpha1
kind: TechnitiumCluster
metadata:
  name: dns
spec:
  replicas: 3
  dnsServerDomain: dns.home.packet.fail
  adminSecretRef:
    name: technitium-admin
  priorityClassName: system-cluster-critical
  storage:
    size: 10Gi
    storageClassName: local-path
    retentionPolicy: Retain
  service:
    type: ClusterIP
    perReplica:
      type: LoadBalancer
      externalTrafficPolicy: Local
      ordinals:
        - ordinal: 0
          annotations:
            metallb.io/loadBalancerIPs: 192.168.74.52
        - ordinal: 1
          annotations:
            metallb.io/loadBalancerIPs: 192.168.74.53
        - ordinal: 2
          annotations:
            metallb.io/loadBalancerIPs: 192.168.74.54
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - topologyKey: kubernetes.io/hostname
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: technitium
              app.kubernetes.io/instance: dns
